In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
# Load JSON from file
with open('data/items.json', 'r') as file:
    dct = json.load(file)
    items = dct["references"]["RefIds"]

with open('data/effects.json', 'r') as file:
    dct = json.load(file)
    effects = dct["references"]["RefIds"]

with open('data/item_types.json', 'r') as file:
    dct = json.load(file)
    item_types = dct["references"]["RefIds"]

with open('data/languages/es.json', 'r') as file:
    names = json.load(file)

with open('data/item_sets.json', 'r') as file:
    dct = json.load(file)
    item_sets = dct["references"]["RefIds"]
    
def get_mapper(dct,context=None,field="rid"):
    mapper = {}
    for d in dct:
        if context is not None:
            mapper[d[context][field]] = d
            continue
        mapper[str(d[field])] = d
    return mapper

mapper_rid = {"items": get_mapper(items),
               "effects": get_mapper(effects),
               "item_types": get_mapper(item_types),
               "item_sets": get_mapper(item_sets),
               "names": names}

In [3]:
# Data parser function
# This function extracts relevant data from the mapper and formats it into a dictionary.
def get_data(mapper,name_field="nameId"):
    data = {}
    for rid, item in mapper.items():
        nameId = str(item["data"].get(name_field, None))
        name = names["entries"].get(nameId, None)
        data[rid] = {"type": item["type"]["class"],
                     "name": name}
        data[rid].update(item["data"].copy())
        # data[rid].update({k:v for k,v in item.items() if k not in data[rid]})
        if "possibleEffects" in data[rid]:
            data[rid]["possibleEffects"] = ",".join([str(i["rid"]) for i in data[rid]["possibleEffects"]["Array"]])
        for field in ["id", "nameId", "typeId", "setId","effectId","characteristic"]:
            if field not in data[rid]:
                continue
            # Ensure that the fields are string
            data[rid][field] = str(data[rid][field])
    return data

In [4]:
def ensure_string_fields(df):
    """Ensure that specific fields in the DataFrame are of string type."""
    for field in ["id", "nameId", "typeId", "set"]:
        if field not in df.columns:
            continue
        # Ensure that the fields are string
        df[field] = df[field].astype(str)

In [5]:
# Effect data
effect_data = get_data(mapper_rid["effects"], name_field="descriptionId")
effect_df = pd.DataFrame.from_dict(effect_data, orient="index")
# Move description to the first column
effect_df = effect_df[["name"] + [col for col in effect_df.columns if col != "name"]]
ensure_string_fields(effect_df)
effect_df.to_csv("data/datasets/effects.csv", index=True)
effect_name_dictionary = effect_df.set_index("id")["name"].to_dict()

In [6]:
# Item type data
item_types = get_data(mapper_rid["item_types"], name_field="nameId")
item_types_df = pd.DataFrame.from_dict(item_types, orient="index")
# Move name to the first column
item_types_df = item_types_df[["name"] + [col for col in item_types_df.columns if col != "name"]]
ensure_string_fields(item_types_df)
item_types_df.to_csv("data/datasets/item_types.csv", index=True)

In [7]:
# Item set data
item_sets = get_data(mapper_rid["item_sets"], name_field="nameId")
item_sets_df = pd.DataFrame.from_dict(item_sets, orient="index")
# Move name to the first column
item_sets_df = item_sets_df[["name"] + [col for col in item_sets_df.columns if col != "name"]]
item_sets_df["items"] = item_sets_df["items"].apply(lambda x: ",".join([str(i) for i in x["Array"]]) if isinstance(x, dict) and "Array" in x else "")
ensure_string_fields(item_types_df)
item_sets_df.to_csv("data/datasets/item_sets.csv", index=True)

In [8]:
# Get a Item to Set mapper
item_to_set_mapper = {}
for rid,row in item_sets_df.iterrows():
    items = row["items"].split(",")
    for item in items:
        if item == "":
            continue
        item_to_set_mapper[item] = rid

In [9]:
# Item data
item_data = get_data(mapper_rid["items"], name_field="nameId")
item_df = pd.DataFrame.from_dict(item_data, orient="index")
# Move name to the first column
item_df = item_df[["name"] + [col for col in item_df.columns if col != "name"]]

# Only change name where there is an effectId
item_df["name"] = item_df["name"].where(item_df["effectId"].isna(),
                                         item_df["effectId"].apply(lambda x: effect_name_dictionary.get(x, "")))
item_df["class"] = item_df["typeId"].apply(lambda x: item_types_df.set_index("id").loc[x, "name"] if item_types_df["id"].isin([x]).any() else x)
item_df["set"] = item_df["id"].apply(lambda x: item_to_set_mapper.get(x, ""))
ensure_string_fields(item_df)
item_df.to_csv("data/datasets/items.csv", index=True)

In [10]:
# Set effects data
set_effects = {}
for rid,row in item_sets_df.iterrows():
    set_effects[rid] = {}
    dct = row["effects"]
    if pd.isna(dct):
        continue
    for idx,v in enumerate(dct["Array"]):
        lst = v["values"]["Array"]
        set_effects[rid][idx+1] = ",".join([str(i["rid"]) for i in lst])

pd.DataFrame.from_dict(set_effects, orient="index").to_csv("data/datasets/set_effects.csv", index=True)

In [11]:
assert False

AssertionError:

### Interpreting

### Effects 
Characteristic -> effect(res/add/subtract) and element

characteristicOperator -> +/-

isInPercent -> % or not

### Items 

diceNum -> minimum stat

diceSide -> maximum stat

typeId -> type of item (cape, hat, etc)

level -> level

criteria -> requirements

criticalHitBonus -> Bonus with crits

criticalHitProbability -> 0 - 100 %

range

castInLine -> 0/1

apCost -> AP to use

maxCastPerTurn

In [ ]:
item_df[[(item_df["typeId"]==2)|(item_df["typeId"]==3)]]

type
EffectInstanceDice    40068
Items                 19946
Weapons                 747
Name: count, dtype: int64

In [12]:
item_df

,name,type,m_flags,id,nameId,typeId,descriptionId,iconId,level,realWeight,...,effectElement,spellId,effectTriggerDuration,zoneDescr,value,diceNum,diceSide,displayZero,class,set
2861093746001846693,Espada de maderucha,Weapons,24712,44,995824,6,995825.0,6007.0,7.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Espada,
2861093746001846694,Espada de hierrucho,Weapons,24712,49,995826,6,33282.0,6002.0,15.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Espada,
2861093746001846695,Espada chifladora,Weapons,24712,55,995827,6,995830.0,6001.0,26.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Espada,
2861093746001846696,La Triste Hoja,Weapons,24712,58,47565,6,47566.0,6005.0,21.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Espada,
2861093746001846697,Espada Dha,Weapons,24712,62,995829,6,1064630.0,6006.0,17.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Espada,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2861093746004781817,¿Qué hay ahí dentro?,EffectInstanceDice,15,nan,nan,nan,NaN,NaN,NaN,NaN,...,-1.0,-1.0,0.0,"{'cellIds': {'Array': []}, 'shape': 67, 'param...",439.0,1.0,0.0,0.0,NaN,
2861093746004781818,Intercambiable: #1,EffectInstanceDice,15,nan,nan,nan,NaN,NaN,NaN,NaN,...,-1.0,-1.0,0.0,"{'cellIds': {'Array': []}, 'shape': 67, 'param...",0.0,0.0,0.0,0.0,NaN,
2861093746004781819,¿Qué hay ahí dentro?,EffectInstanceDice,15,nan,nan,nan,NaN,NaN,NaN,NaN,...,-1.0,-1.0,0.0,"{'cellIds': {'Array': []}, 'shape': 67, 'param...",440.0,1.0,0.0,0.0,NaN,
2861093746004781820,Intercambiable: #1,EffectInstanceDice,15,nan,nan,nan,NaN,NaN,NaN,NaN,...,-1.0,-1.0,0.0,"{'cellIds': {'Array': []}, 'shape': 67, 'param...",0.0,0.0,0.0,0.0,NaN,
2861093746004781821,¿Qué hay ahí dentro?,EffectInstanceDice,15,nan,nan,nan,NaN,NaN,NaN,NaN,...,-1.0,-1.0,0.0,"{'cellIds': {'Array': []}, 'shape': 67, 'param...",441.0,1.0,0.0,0.0,NaN,

In [ ]:
effect_df[effect_df["name"].str.contains("resistencia.*agua", na=False)]

,name,type,id,descriptionId,iconId,characteristic,category,characteristicOperator,showInTooltip,useDice,...,bonusType,useInFight,effectPriority,effectPowerRate,elementId,isInPercent,hideValueInTooltip,textIconReferenceId,effectTriggerDuration,actionFiltersId
2861093746001578911,#1{{~1~2 a }}#2% resistencia al agua,Effects,211,1067166,0,35,1,+,0,1,...,1,0,9700,6.0,-1,1,0,34,0,"{'Array': [6, 10, 13]}"
2861093746001578916,-#1{{~1~2 a -}}#2% resistencia al agua,Effects,216,1067168,0,35,1,-,0,1,...,-1,0,10200,-3.0,-1,1,0,34,0,"{'Array': [6, 12]}"
2861093746001578931,#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} al ...,Effects,241,1067167,0,56,1,+,0,1,...,1,0,10700,2.0,-1,0,0,34,0,"{'Array': [13, 10, 6]}"
2861093746001578936,-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} a...,Effects,246,1067169,0,56,1,-,0,1,...,-1,0,103600,-1.0,-1,0,0,34,0,"{'Array': [6, 12]}"

In [ ]:
for i in sorted(effect_df["characteristic"].unique()):
    if i == 0:
        continue
    print(i, effect_df[effect_df["characteristic"]==i]["name"].unique())

1 ['-#1{{~1~2 a -}}#2 PA' '#1{{~1~2 a }}#2 PA'
 '-#1{{~1~2 a }}#2 PA para el lanzador']
10 ['#1{{~1~2 a }}#2 fuerza' '-#1{{~1~2 a -}}#2 fuerza'
 '#1{{~1~2 a -}}#2 robo de fuerza' '+#1 de fuerza adicional']
11 ['#1{{~1~2 a }}#2 vitalidad' '-#1{{~1~2 a -}}#2 vitalidad'
 '#1{{~1~2 a -}}#2 robo de vitalidad' '+#1 vitalidad'
 '-#1{{~1~2 a -}}#2% vitalidad' '#1{{~1~2 a }}#2% vitalidad']
12 ['#1{{~1~2 a }}#2 sabiduría' '-#1{{~1~2 a -}}#2 sabiduría'
 '#1{{~1~2 a -}}#2 robo de sabiduría' '+#1 sabiduría']
13 ['#1{{~1~2 a }}#2 suerte' '-#1{{~1~2 a -}}#2 suerte'
 '#1{{~1~2 a -}}#2 robo de suerte' '+#1 suerte']
14 ['#1{{~1~2 a }}#2 agilidad' '-#1{{~1~2 a -}}#2 agilidad'
 '#1{{~1~2 a -}}#2 robo de agilidad' '+#1 de agilidad adicional']
15 ['#1{{~1~2 a }}#2 inteligencia' '-#1{{~1~2 a -}}#2 inteligencia'
 '#1{{~1~2 a -}}#2 robo de inteligencia' '+#1 inteligencia']
16 ['-#1{{~1~2 a }}#2 de daños recibidos'
 '#1{{~1~2 a }}#2 de daño{{~p}}{{~z}}' '#1{{~1~2 a }}#2 daños'
 'Daños físicos del lanzador aumentados: #1{{~1~2 a }}#2'
 '+#1{{~1~2 a }}#2 daños físicos' '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}}'
 '#2% daños #1']
18 ['#1{{~1~2 a }}#2 % crítico' '-#1{{~1~2 a -}}#2% crítico']
19 ['-#1{{~1~2 a -}}#2 alcance' '#1{{~1~2 a }}#2 alcance'
 '+#1{{~1~2 a }}#2 de alcance (lanzador)']
20 ['-#1{{~1~2 a -}}#2 de reducción mágica'
 '#1{{~1~2 a }}#2 reducción mágica']
21 ['-#1{{~1~2 a -}}#2 de reducción física'
 '#1{{~1~2 a }}#2 reducción física']
23 ['-#1{{~1~2 -}}#2 PM' '#1{{~1~2 a }}#2 PM'
 '-#1{{~1~2 a }}#2 PM para el lanzador' '-#1{{~1~2 a -}}#2 PM']
24 ['Vuelve invisible al objetivo']
25 ['#1{{~1~2 a }}#2 potencia (daños generales)' '-#1{{~1~2 a -}}#2 potencia']
26 ['#1{{~1~2 a }}#2 invocaciones{{~p}}{{~z}}'
 '-#1{{~1~2 a }}#2 invocaciones{{~p}}{{~z}}']
27 ['#1{{~1~2 a }}#2 a la esquiva pérdidas de PA'
 '-#1{{~1~2 a -}}#2 esquiva de PA']
28 ['#1{{~1~2 a }}#2 a la esquiva pérdidas de PM'
 '-#1{{~1~2 a -}}#2 esquiva PM']
29 ['Devuelve #1{{~1~2 a }}#2 punto{{~ps}}{{~zs}} de energía']
30 ['Reenvía un hechizo']
31 ['#1{{~1~2 a }}#2 de daños devueltos']
33 ['#1{{~1~2 a }}#2% resistencia a la tierra'
 '-#1{{~1~2 a -}}#2% resistencia a la tierra']
34 ['#1{{~1~2 a }}#2% resistencia al fuego'
 '-#1{{~1~2 a -}}#2% resistencia al fuego']
35 ['#1{{~1~2 a }}#2% resistencia al agua'
 '-#1{{~1~2 a -}}#2% resistencia al agua']
36 ['#1{{~1~2 a }}#2% resistencia al aire'
 '-#1{{~1~2 a -}}#2% resistencia al aire']
37 ['#1{{~1~2 a }}#2% resistencia neutral'
 '-#1{{~1~2 a -}}#2% resistencia neutral']
38 ['Cambia las palabras' 'Cambia la apariencia' 'Cambia un color.']
39 ['#1{{~1~2 a }}#2 FC']
40 ['#1{{~1~2 a }}#2 pod{{~ps}}{{~zs}}' None]
44 ['#1{{~1~2 a }}#2 iniciativa' '-#1{{~1~2 a -}}#2 iniciativa']
48 ['#1{{~1~2 a }}#2 prospección' '-#1{{~1~2 a -}}#2 prospección']
49 ['#1{{~1~2 a }}#2 de cura{{~p}}{{~z}}'
 '-#1{{~1~2 a -}}#2 de cura{{~p}}{{~z}}'
 'Aumenta un #1% las curas finales ocasionadas' '-#1% de curas finales']
50 ['#1{{~1~2 a }}#2 de daños devueltos']
51 ['#1 de energía perdida']
52 ['#3 puntos de honor' 'Quita #3 puntos de honor']
54 ['#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} a la tierra'
 '-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} a la tierra']
55 ['#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} al fuego'
 '-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} al fuego']
56 ['#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} al agua'
 '-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} al agua']
57 ['#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} al aire'
 '-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} al aire']
58 ['#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} al neutro'
 '-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} al neutro']
69 ['#1{{~1~2 a }}#2 potencia (daños generales) con trampas']
70 ['#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} de trampas']
71 ['Estado #3' 'Quita el estado «#3»' 'Desactiva el estado #3']
72 ['+#1{{~1~2 a }}#2% de probabilidad de captura']
73 ['#1{{~1~2 a }}#2% <sprite name="XP"> de montura']
74 ['Confusión sentido horario: #1{{~1~2 a }}#2 grados'
 'Confusión horaria: #1{{~1~2 a }}#2 Pi/2'
 'Confusión sentido horario: #1{{~1~2 a }}#2 Pi/4'
 'Confusión sentido antihorario: #1{{~1~2 a }}#2 grados'
 'Confusión sentido antihorario: #1{{~1~2 a }}#2 Pi/2'
 'Confusión sentido antihorario: #1{{~1~2 a }}#2 Pi/4']
75 ['#1{{~1~2 a }}#2% daños sufridos incurables'
 '-#1{{~1~2 a }}#2% de erosión'
 '#1{{~1~2 a }}#2 puntos de vida erosionados'
 '#1{{~1~2 a }}#2% de puntos de vida erosionados'
 '-#1{{~1~2 a }}#2 puntos de vida erosionados'
 '-#1{{~1~2 a }}#2% de puntos de vida erosionados']
78 ['#1{{~1~2 a }}#2 huida' '-#1{{~1~2 a -}}#2 huida']
79 ['#1{{~1~2 a }}#2 placaje' '-#1{{~1~2 a -}}#2 placaje']
80 ['Agrede a los personajes de alianzas enemigas automáticamente']
81 ['Resistencia a la agresión automática de manos de jugadores enemigos: #1{{~1~2 a }}#2']
82 ['#1{{~1~2 a }}#2 al retiro de PA' '-#1{{~1~2 a -}}#2 supresión PA']
83 ['#1{{~1~2 a }}#2 al retiro de PM' '-#1{{~1~2 a -}}#2 supresión PM']
84 ['#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} de empuje'
 '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}} de empuje']
85 ['#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} al empuje'
 '-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} al empuje']
86 ['#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} crítico'
 '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}} crítico']
87 ['#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} a los críticos'
 '-#1{{~1~2 a -}}#2 de resistencia{{~p}}{{~z}} a críticos']
88 ['#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} de tierra'
 '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}} de tierra']
89 ['#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} de fuego'
 '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}} de fuego']
90 ['#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} de agua'
 '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}} de agua']
91 ['#1{{~1~2 a }}#2 de daño{{~ps}}{{~zs}} de aire'
 '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}} de aire']
92 ['#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} neutro'
 '-#1{{~1~2 a -}}#2 de daño{{~p}}{{~z}} neutro']
98 ['#1{{~1~2 a }}#2 potencia (daños generales) de hechizos']
99 ['Tamaño: #1{{~1~2 a }}#2']
100 ['Turno cancelado' 'Combate anulado']
101 ['#1{{~1~2 a }}#2 % resistencia' '-#1{{~1~2 a -}}#2 % resistencia']
103 ['#1{{~1~2 a }}#2 potencia (daños generales) con armas']
106 ['#1{{~1~2 a }}#2 potencia (daños generales) con glifos']
107 ['#1% de daños finales' '-#1% de daños finales']
108 ['Elimina las ganancias de experiencia']
110 ['#1{{~1~2 a }}#2 potencia (runas)']
120 ['#1{{~1~2 a }}#2% daños distancia' '-#1{{~1~2 a -}}#2% daños distancia']
121 ['-#1{{~1~2 a -}}#2% resistencia distancia'
 '#1{{~1~2 a }}#2% resistencia distancia']
122 ['#1{{~1~2 a }}#2 % daños de armas' '-#1{{~1~2 a -}}#2 % daños de armas']
123 ['#1{{~1~2 a }}#2% daños a los hechizos'
 '-#1{{~1~2 a -}}#2 % daños de hechizos']
124 ['-#1{{~1~2 a -}}#2% resistencia CaC' '#1{{~1~2 a }}#2% resistencia CaC']
125 ['#1{{~1~2 a }}#2% daños CaC' '-#1{{~1~2 a -}}#2% daños CaC']
126 ['#1{{~1~2 a }}#2% agilidad' '-#1{{~1~2 a -}}#2% agilidad']
127 ['#1{{~1~2 a }}#2% fuerza' '-#1{{~1~2 a -}}#2% fuerza']
128 ['#1{{~1~2 a }}#2% suerte' '-#1{{~1~2 a -}}#2% suerte']
129 ['#1{{~1~2 a }}#2% inteligencia' '-#1{{~1~2 a -}}#2% inteligencia']
130 ['#1{{~1~2 a }}#2% vitalidad' '-#1{{~1~2 a -}}#2% vitalidad']
131 ['#1{{~1~2 a }}#2% sabiduría' '-#1{{~1~2 a -}}#2% sabiduría']
132 ['#1{{~1~2 a }}#2% placaje' '-#1{{~1~2 a -}}#2% placaje']
133 ['#1{{~1~2 a }}#2% huida' '-#1{{~1~2 a -}}#2% huida']
134 ['#1{{~1~2 a }}#2% PA' '-#1{{~1~2 a -}}#2% PA']
135 ['#1{{~1~2 a }}#2% PM' '-#1{{~1~2 a -}}#2% PM']
136 ['#1{{~1~2 a }}#2% retirada de PA' '-#1{{~1~2 a -}}#2% retirada de PA']
137 ['#1{{~1~2 a }}#2% retirada de PM' '-#1{{~1~2 a -}}#2% retirada de PM']
138 ['#1{{~1~2 a }}#2% esquiva de PA' '-#1{{~1~2 a -}}#2% esquiva de PA']
139 ['#1{{~1~2 a }}#2% esquiva de PM' '-#1{{~1~2 a -}}#2% esquiva de PM']
140 ['Tamaño: +#1{{~1~2 a }}#2%' 'Tamaño: -#1{{~1~2 a }}#2%']
141 ['-#1{{~1~2 a -}}#2% resistencia a hechizos'
 '#1{{~1~2 a }}#2% resistencia a hechizos']
142 ['-#1{{~1~2 a -}}#2% resistencia a armas'
 '#1{{~1~2 a }}#2% resistencia a armas']

In [ ]:
effect_df[effect_df["characteristic"].isin(range(10,16))]

,name,type,id,descriptionId,iconId,characteristic,category,characteristicOperator,showInTooltip,useDice,...,bonusType,useInFight,effectPriority,effectPowerRate,elementId,isInPercent,hideValueInTooltip,textIconReferenceId,effectTriggerDuration,actionFiltersId
2861093746001578832,#1{{~1~2 a }}#2 fuerza,Effects,118,1067135,0,10,0,+,0,1,...,1,0,5300,1.0,1,0,0,5,0,"{'Array': [7, 13]}"
2861093746001578833,#1{{~1~2 a }}#2 agilidad,Effects,119,1067139,0,14,0,+,0,1,...,1,0,5900,1.0,4,0,0,6,0,"{'Array': [4, 13]}"
2861093746001578837,#1{{~1~2 a }}#2 suerte,Effects,123,1066395,0,13,0,+,0,1,...,1,0,5700,1.0,3,0,0,3,0,"{'Array': [6, 13]}"
2861093746001578838,#1{{~1~2 a }}#2 sabiduría,Effects,124,1066476,0,12,0,+,0,1,...,1,0,6100,3.0,-1,0,0,29,0,{'Array': [13]}
2861093746001578839,#1{{~1~2 a }}#2 vitalidad,Effects,125,1066464,0,11,0,+,0,1,...,1,0,5000,0.2,-1,0,0,10,0,{'Array': [13]}
2861093746001578840,#1{{~1~2 a }}#2 inteligencia,Effects,126,1067133,0,15,0,+,0,1,...,1,0,5500,1.0,2,0,0,4,0,"{'Array': [5, 13]}"
2861093746001578862,-#1{{~1~2 a -}}#2 suerte,Effects,152,1066497,0,13,0,-,0,1,...,-1,0,5800,-0.5,3,0,0,3,0,"{'Array': [6, 12]}"
2861093746001578863,-#1{{~1~2 a -}}#2 vitalidad,Effects,153,1068521,0,11,0,-,0,1,...,-1,0,5100,-0.1,-1,0,0,10,0,{'Array': [12]}
2861093746001578864,-#1{{~1~2 a -}}#2 agilidad,Effects,154,1068112,0,14,0,-,0,1,...,-1,0,6000,-0.5,4,0,0,6,0,"{'Array': [4, 12]}"
2861093746001578865,-#1{{~1~2 a -}}#2 inteligencia,Effects,155,1068107,0,15,0,-,0,1,...,-1,0,5600,-0.5,2,0,0,4,0,"{'Array': [5, 12]}"
2861093746001578866,-#1{{~1~2 a -}}#2 sabiduría,Effects,156,1072876,0,12,0,-,0,1,...,-1,0,6200,-1.5,-1,0,0,29,0,{'Array': [12]}
2861093746001578867,-#1{{~1~2 a -}}#2 fuerza,Effects,157,1068102,0,10,0,-,0,1,...,-1,0,5400,-0.5,1,0,0,5,0,"{'Array': [7, 12]}"
2861093746001578941,#1{{~1~2 a -}}#2 robo de suerte,Effects,266,1066499,0,13,0,,0,1,...,0,0,0,0.0,-1,0,0,3,0,"{'Array': [6, 13, 12]}"
2861093746001578942,#1{{~1~2 a -}}#2 robo de vitalidad,Effects,267,1068525,0,11,0,,0,1,...,0,0,0,0.0,-1,0,0,10,0,"{'Array': [13, 12]}"
2861093746001578943,#1{{~1~2 a -}}#2 robo de agilidad,Effects,268,1068114,0,14,0,,0,1,...,0,0,0,0.0,-1,0,0,6,0,"{'Array': [4, 13, 12]}"
2861093746001578944,#1{{~1~2 a -}}#2 robo de inteligencia,Effects,269,1068109,0,15,0,,0,1,...,0,0,0,0.0,-1,0,0,4,0,"{'Array': [5, 13, 12]}"
2861093746001578945,#1{{~1~2 a -}}#2 robo de sabiduría,Effects,270,1072878,0,12,0,,0,1,...,0,0,0,0.0,-1,0,0,29,0,"{'Array': [13, 12]}"
2861093746001578946,#1{{~1~2 a -}}#2 robo de fuerza,Effects,271,1068110,0,10,0,,0,1,...,0,0,0,0.0,-1,0,0,5,0,"{'Array': [7, 13, 12]}"
2861093746001579022,+#1 sabiduría,Effects,606,1104626,0,12,0,+,0,1,...,0,0,19600,100.0,-1,0,0,29,0,{'Array': []}
2861093746001579023,+#1 de fuerza adicional,Effects,607,1104625,0,10,0,+,0,1,...,0,0,19200,100.0,-1,0,0,5,0,{'Array': []}
2861093746001579024,+#1 suerte,Effects,608,1104624,0,13,0,+,0,1,...,0,0,19400,100.0,-1,0,0,3,0,{'Array': []}
2861093746001579025,+#1 de agilidad adicional,Effects,609,1104623,0,14,0,+,0,1,...,0,0,19500,100.0,-1,0,0,6,0,{'Array': []}
2861093746001579026,+#1 vitalidad,Effects,610,1104627,0,11,0,+,0,1,...,0,0,19100,100.0,-1,0,0,10,0,{'Array': []}
2861093746001579027,+#1 inteligencia,Effects,611,1104622,0,15,0,+,0,1,...,0,0,19300,100.0,-1,0,0,4,0,{'Array': []}
2861093746001579188,-#1{{~1~2 a -}}#2% vitalidad,Effects,1033,1091443,0,11,0,-,0,1,...,0,0,0,0.0,-1,1,0,10,0,{'Array': [12]}
2861093746001579227,#1{{~1~2 a }}#2% vitalidad,Effects,1078,1066461,0,11,0,+,0,1,...,0,0,0,0.0,-1,1,0,10,0,{'Array': [13]}

In [ ]:
item_df[item_df["typeId"]==18]["name"]

2861093746004721881                     Wauwau
2861093746004721896                   Miaumiau
2861093746004721913                     Wabbit
2861093746004722093              Bwak de fuego
2861093746004722094               Bwak de agua
                                ...
2861093746004732910                    Molocán
2861093746004738370    Joven jalatín celestial
2861093746004740705           Jalatrool blanco
2861093746004741570                 Raribichón
2861093746004741592               Microsmoglob
Name: name, Length: 122, dtype: object

In [ ]:
item_df[item_df["name"].str.contains("Capa", na=False)]

,name,type,m_flags,id,nameId,typeId,descriptionId,iconId,level,realWeight,...,delay,triggers,effectElement,spellId,effectTriggerDuration,zoneDescr,value,diceNum,diceSide,displayZero
2861093746001846997,Capa de pirata,Items,24712,677.0,78774.0,17.0,47260.0,17011.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847040,Capa de Bowis,Items,24712,744.0,35685.0,17.0,35686.0,17001.0,20.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847048,Capa de vampiro,Items,24712,754.0,42701.0,17.0,42702.0,17017.0,29.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847051,Capa de justiciero,Items,24712,758.0,261306.0,17.0,966930.0,17002.0,30.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847052,Capa de pohoyo titiritasado,Items,24712,759.0,78716.0,17.0,78717.0,17003.0,33.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2861093746004741268,Capa matizada del Demonio I,Items,24584,31539.0,1129419.0,247.0,1129435.0,17645.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741461,Caparazón alado del Bzupervibzor,Items,24712,31750.0,1138744.0,17.0,1142458.0,17655.0,178.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741601,Capa de la Demonio II,Items,24584,31896.0,1144700.0,247.0,1144710.0,17643.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741605,Capa matizada de la Demonio II,Items,24584,31900.0,1144708.0,247.0,1144711.0,17644.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741612,Capa de agente de viajes,Items,24584,31907.0,1141632.0,247.0,1141783.0,17656.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
item_df[item_df["typeId"]==17]

,name,type,m_flags,id,nameId,typeId,descriptionId,iconId,level,realWeight,...,delay,triggers,effectElement,spellId,effectTriggerDuration,zoneDescr,value,diceNum,diceSide,displayZero
2861093746001846997,Capa de pirata,Items,24712,677.0,78774.0,17.0,47260.0,17011.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847040,Capa de Bowis,Items,24712,744.0,35685.0,17.0,35686.0,17001.0,20.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847048,Capa de vampiro,Items,24712,754.0,42701.0,17.0,42702.0,17017.0,29.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847051,Capa de justiciero,Items,24712,758.0,261306.0,17.0,966930.0,17002.0,30.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746001847052,Capa de pohoyo titiritasado,Items,24712,759.0,78716.0,17.0,78717.0,17003.0,33.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2861093746004738481,Capa Anteón,Items,24584,27552.0,971968.0,17.0,982345.0,17567.0,80.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741461,Caparazón alado del Bzupervibzor,Items,24712,31750.0,1138744.0,17.0,1142458.0,17655.0,178.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741480,Portal de los viajeros,Items,24712,31769.0,1138818.0,17.0,1141867.0,81075.0,197.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741504,Cesta de bzuevos,Items,24712,31793.0,1141009.0,17.0,1141841.0,81074.0,172.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861093746004741508,Abrigo del Venerable Durmiente,Items,24712,31797.0,1139029.0,17.0,1142571.0,17657.0,200.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN