In [19]:
import pandas as pd
from itertools import chain
from functools import reduce

### Load

In [20]:
def load_csv(file_path):
    """Load a CSV file into a DataFrame."""
    df = pd.read_csv(file_path,index_col=0)
    for field in ["id", "nameId", "typeId", "setId"]:
        if field not in df.columns:
            continue
        # Ensure that the fields are string
        df[field] = df[field].astype(str)
    return df

In [21]:
items = load_csv("data/datasets/items.csv")
effects = load_csv("data/datasets/effects.csv").set_index("id")
types = load_csv("data/datasets/types.csv")

/var/folders/c3/9yq4kl5j7qd715s6mq5tyslm0000gp/T/ipykernel_86024/4237221942.py:3: DtypeWarning: Columns (1,2,14,15,19,20,21,22,23,24,27,28,29,30,32,33,63) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path,index_col=0)

In [18]:
items[items["id"]=="2411"]

Empty DataFrame
Columns: [name, type, m_flags, id, nameId, typeId, descriptionId, iconId, level, realWeight, useAnimationId, price, itemSetId, criteria, criteriaTarget, appearanceId, isColorable, recipeSlots, recipeIds, dropMonsterIds, dropTemporisMonsterIds, possibleEffects, evolutiveEffectIds, favoriteSubAreas, favoriteSubAreasBonus, craftXpRatio, craftVisible, craftConditional, craftFeasible, visibility, recyclingNuggets, favoriteRecyclingSubareas, resourcesBySubarea, importantNoticeId, changeVersion, tooltipExpirationDate, criticalFailureProbability, criticalHitBonus, minRange, criticalHitProbability, range, castInLine, apCost, castInDiagonal, castTestLos, maxCastPerTurn, effectUid, baseEffectId, effectId, order, targetId, targetMask, duration, random, group, modificator, dispellable, delay, triggers, effectElement, spellId, effectTriggerDuration, zoneDescr, value, diceNum, diceSide, displayZero, set]
Index: []

[0 rows x 68 columns]

In [14]:
items[items["set"]==2861093746001593292]

,name,type,m_flags,id,nameId,typeId,descriptionId,iconId,level,realWeight,...,triggers,effectElement,spellId,effectTriggerDuration,zoneDescr,value,diceNum,diceSide,displayZero,set
2861093746001846731,Krystobola,Bastón,24712,204.0,51301.0,4.0,51302.0,4063.0,68.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746001847017,Crystalobola,Sombrero,24712,706.0,48909.0,16.0,48910.0,16012.0,72.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746001847191,Corona del Wey Wabbit,Sombrero,24712,969.0,48463.0,16.0,48464.0,16021.0,60.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746001847192,Bastón del Wey Wabbit,Bastón,24712,970.0,33483.0,4.0,33484.0,4021.0,60.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746001847193,Capa del Wey Wabbit,Capa,24712,971.0,48423.0,17.0,300097.0,17021.0,60.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2861093746004732272,Escudo de jefe cocodrail,Escudo,24712,18713.0,721400.0,82.0,721401.0,82154.0,70.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746004740475,Escudo erizado de prespic,Escudo,24712,30681.0,1118526.0,82.0,1118520.0,82514.0,35.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746004740481,Coraza real de jalató,Escudo,24712,30687.0,1105642.0,82.0,1115717.0,82512.0,30.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746004741239,Armadura de campeón,Traje,24584,31509.0,1128469.0,199.0,1128477.0,164242.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18
2861093746004741240,Hombreras de campeón,Hombreras,24712,31510.0,1128472.0,299.0,1128475.0,164241.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.861094e+18