## Recommended Starting Hyperparameters
1. Population Size
* Typical Range: 50–500.
* Recommendation: Start with 100–200.
* Larger populations explore more, but are slower per generation.
* With your large search space, erring toward the higher end (e.g., 200) is reasonable if your fitness function is fast.

2. Number of Generations
* Typical Range: 50–500+.
* Recommendation: 100–300 generations.
* More generations allow more refinement, but diminishing returns after a point.
* You can monitor if the best fitness plateaus early.
3. Selection Method
* Tournament selection or roulette wheel selection are both good.
* Many libraries use tournament selection by default.
4. Crossover Rate
* Typical: 0.7–0.9 (i.e., 70–90% of offspring are produced by crossover).
* Recommendation: 0.8 (80%).
5. Mutation Rate
* Typical: 0.01–0.1 (1–10% mutation rate per gene).
* Recommendation: 0.05 (5% per gene).
* With 9 genes (slots), this means about half your children will have at least one mutation per generation.
6. Elitism
* Keep the best 1–2 individuals from each generation to ensure you don’t lose the best found so far.

In [1]:
import pandas as pd
from itertools import chain
from functools import reduce

In [2]:
# Hyperparameters
POPULATION_SIZE = 150
NUM_GENERATIONS = 200
MUTATION_RATE = 0.05
EXCLUSIONS = {
    "items" : [6894,6895,3080,9031]
}
LOWER_BOUNDS = {
    # "level" : 190
}
UPPER_BOUNDS = {}

### Load

In [3]:
import json
with open('data/MAPPED_ITEMS.json', 'r') as file:
    items = {i["ankama_id"]: i for i in json.load(file)}

with open('data/MAPPED_SETS.json', 'r') as file:
    item_sets = {i["ankama_id"]: i for i in json.load(file)}

### Filters

In [4]:
items = {k:v for k,v in items.items() if not k in EXCLUSIONS["items"]}

In [5]:
pool_types = [
    (1, 1),
    (2, 1),
    (3, 2), # Ring
    (4, 1),
    (5, 1),
    (7, 1),
    (10,1),
    (11, 1),
    (12, 1),
    (13, 6),
]
pools = []
for t,count in pool_types:
    for i in range(count):
        pools.append([id for id in items if items[id]["type"]["superTypeId"] == t])
NUM_TYPES = len(pools)
print(f"Total pools: {len(pools)} with sizes {[len(pool) for pool in pools]}")

Total pools: 16 with sizes [322, 747, 369, 369, 354, 364, 178, 366, 301, 145, 327, 327, 327, 327, 327, 327]

## Effect logic dictionaries

In [9]:
def get_item_contribution(item):
    # Get the effects of the item
    item_effects = item["effects"]
    if not item_effects:
        return {}
    contributions = {}
    for d in item_effects:
        field = "max" if d["min_max_irrelevant"] == 0 else "min"
        contributions[d["element_id"]] = d[field]
    return contributions

In [10]:
def get_item_set(item):
    if not item["hasParentSet"]:
        return None
    return item_sets[item["parentSet"]["id"]]

In [11]:
def get_set_contribution(item_set,overlap):
    set_effects = item_set["effects"][str(overlap)]
    contributions = {}
    for d in set_effects:
        field = "max" if d["min_max_irrelevant"] == 0 else "min"
        contributions[d["element_id"]] = d[field]
    return contributions

## Damage logic

In [12]:
# Interpreters/Mappers to characteristics per element
damage_mapper = {
    # Damage
        189 : 36, # Air,
        214 : 22, # Water
        198 : 13, # Fire
        194 : 45, # Earth
        195 : 45, # Neutral (by earth)
    # Steal
        224 : 36, # Air,
        203 : 22, # Water
        193 : 13, # Fire
        221 : 45, # Earth
        223 : 45, # Neutral
    }

bonus_damage_mapper = {
    # Damage
        189 : 47, # Air,
        214 : 27, # Water
        198 : 61, # Fire
        194 : 48, # Earth
        195 : 49, # Neutral
    # Steal
        224 : 47, # Air,
        203 : 27, # Water
        193 : 61, # Fire
        221 : 48, # Earth
        223 : 49, # Neutral
}

In [13]:
def get_weapon_damage(weapon):
    if not weapon["effects"]:
        return {}
    damage_effects = [d for d in weapon["effects"] if d["active"]]
    if not damage_effects:
        return {}
    contributions = {}
    for d in damage_effects:
        field = "max" if d["min_max_irrelevant"] == 0 else "min"
        contributions[d["element_id"]] = d[field]
    return contributions

## 0. Methods

In [14]:
import random
def random_chromosome():
    return [random.randint(0, len(slot_pool)-1) for slot_pool in pools]

In [15]:
# Mutation
def mutate(chromosome, mutation_rate=MUTATION_RATE):
    # Create a new chromosome by mutating some slots
    new_chromosome = chromosome[:]
    for i, slot_items in enumerate(pools):
        if random.random() < mutation_rate:
            new_chromosome[i] = random.randint(0, len(slot_items)-1)
    return new_chromosome

In [16]:
# Crossover
def crossover(parent1, parent2):
    # Perform single-point crossover
    point = random.randint(1, NUM_TYPES-2)
    return parent1[:point] + parent2[point:]

In [17]:
def get_chromosome_weapon(chromosome):
    return next(items[pools[idx][i]] for idx,i in enumerate(chromosome) if items[pools[idx][i]]["type"]["superTypeId"] == 2)

In [17]:
def get_chromosome_item_contributions(chromosome):
    # Item contributions
    chromosome_items = [items[pools[idx][i]] for idx,i in enumerate(chromosome)]
    lst = [get_item_contribution(item) for item in chromosome_items]
    return pd.DataFrame(lst).sum(axis=0).to_dict()

def get_chromosome_set_contributions(chromosome):
    chromosome_items = [items[pools[idx][i]] for idx,i in enumerate(chromosome)]
    # Set effects contributions
    lst = []
    seen_sets = set()
    for item in chromosome_items:
        item_set = get_item_set(item)
        if item_set is None:
            continue
        if item_set["ankama_id"] in seen_sets:
            continue
        seen_sets.add(item_set["ankama_id"])
        overlap = len(set([i["ankama_id"] for i in chromosome_items]) & set(item_set["items"]))
        lst.append(get_set_contribution(item_set, overlap))
    return pd.DataFrame(lst).sum(axis=0).to_dict()

In [18]:
# Fitness function
def get_totals(chromosome):
    # Get the item contributions
    item_contributions = get_chromosome_item_contributions(chromosome)

    # Get the set contributions
    set_contributions = get_chromosome_set_contributions(chromosome)
    return pd.DataFrame([item_contributions, set_contributions]).sum(axis=0).to_dict()

In [19]:
def get_damage(weapon, chromosome):
    totals = get_totals(chromosome)

    # Character stats
    power = totals.get("32",0)
    base_crit_chance = totals.get("29",0)
    base_crit_added_damage = totals.get("38",0)

    # Critical hit logic
    crit_bonus = weapon["criticalHitBonus"] if not pd.isna(weapon["criticalHitBonus"]) else 0
    weapon_crit_chance = weapon["criticalHitProbability"] if not pd.isna(weapon["criticalHitProbability"]) else 0
    crit_chance = max(min(weapon_crit_chance + base_crit_chance,100), 0)  # Ensure crit_chance is between 0 and 100
    expected_crit_bonus = max(crit_bonus * crit_chance/100, 0) # Expected value of distributionß
    expected_crit_added_damage = max(base_crit_added_damage * crit_chance/100, 0) # Expected value of distribution
    # max_crit_bonus = crit_bonus # Use this for maximum possible

    weapon_damage = get_weapon_damage(weapon)
    # Calculate total damage
    damage = 0
    for element_id,weapon_base_damage in weapon_damage.items():
        # Get the stat and base damage
        if element_id not in damage_mapper:
            continue
        stat = damage_mapper[element_id]
        stat_base = totals.get(stat,0)

        # Get the added bonus damage from the stat
        bonus_damage_id = bonus_damage_mapper[element_id]
        added_bonus = totals.get(bonus_damage_id, 0)
        damage += (weapon_base_damage + expected_crit_bonus) * (1+(stat_base+power)/100) + expected_crit_added_damage + added_bonus
    return damage

In [20]:
def fitness(chromosome):
    # Penalizations
    if len(set(chromosome[-pool_types[-1][1]:])) < pool_types[-1][1]:
        # Some dofus or trophies are duplicated
        return 0
    if len(set(chromosome[2:4])) < 2:
        # Some rings are duplicated
        return 0
    # TODO: Penalize two rings
    # return get_totals(chromosome).get(18, 0)
    weapon = get_chromosome_weapon(chromosome)
    return get_damage(weapon,chromosome)

In [21]:
# Sanity check to make sure the function works on random chromosomes
for _ in range(10):
    chromosome = random_chromosome()
    assert isinstance(fitness(chromosome), float) or isinstance(fitness(chromosome), int)

## 1. Initialize population

In [22]:
population = [random_chromosome() for _ in range(POPULATION_SIZE)]

## 2. Selection

In [23]:
def select(population, k=10):
    # Select top k chromosomes
    scored = sorted(population, key=fitness, reverse=True)
    return scored[:k]

## 3. Main Loop

In [24]:
from tqdm import tqdm
for gen in tqdm(range(NUM_GENERATIONS), desc="Generations"):
    # Select best individuals
    selected = select(population, k=10)
    # Generate new population
    new_population = selected[:]
    while len(new_population) < POPULATION_SIZE:
        parent1, parent2 = random.sample(selected, 2)
        child = crossover(parent1, parent2)
        child = mutate(child)
        new_population.append(child)
    population = new_population
    # Print best fitness in this generation
    best = max(population, key=fitness)
    # print(f'Gen {gen}: Best damage = {fitness(best)}')

Generations: 100%|██████████| 200/200 [00:49<00:00,  4.02it/s]

In [ ]:
fitness(best)

1479.775

In [25]:
best_items = [items[pools[idx][i]] for idx,i in enumerate(best)]
[(i["type"]["name"]["es"],i["name"]["es"])for i in best_items]

[('Amuleto', 'Collar de tritáceo'),
 ('Espada', 'Nueve Colas'),
 ('Anillo', 'Anillo del conde Kontatrás'),
 ('Anillo', 'Anillo crústico'),
 ('Cinturón', 'Bosque del lich'),
 ('Bota', 'Botas del conde Kontatrás'),
 ('Escudo', 'Paravela de Mami Ayuto'),
 ('Sombrero', 'Pañoleta de Mami Ayuto'),
 ('Capa', 'Capa Pología'),
 ('Mascotura', 'Kompost'),
 ('Trofeo', 'Hércules'),
 ('Trofeo', 'Rabioso mayor'),
 ('Trofeo', 'Hércules mayor'),
 ('Dofus', 'Dolmanax'),
 ('Trofeo', 'Rabioso'),
 ('Trofeo', 'Furibundo mayor')]

In [26]:
lst = [get_item_contribution(i) for i in best_items]
df = pd.DataFrame(lst,index=[i["name"]["es"] for i in best_items])

In [27]:
# Count the sets
set_counts = pd.Series([i["parentSet"]["name"]["es"] for i in best_items if i["hasParentSet"]]).value_counts()
set_counts

Set de la sima                    2
Set del conde Kontatrás           2
Set de Mami Ayuto                 2
Reliquias de la Aurora Púrpura    1
Name: count, dtype: int64

In [28]:
item_descriptions = {}
for _,item in items.items():
    if not item["effects"]:
        continue
    for effect in item["effects"]:
        item_descriptions[effect["element_id"]] = effect["type"]["es"]

In [29]:
for k,v in get_totals(best).items():
    print(f"({k}) {item_descriptions[k]}: {v}")

(9) vitalidad: 3099.0
(45) fuerza: 1449.0
(10) sabiduría: 305.0
(25) prospección: 15.0
(48) de daño de tierra: 120.0
(49) de daño neutro: 100.0
(16) % resistencia al aire: 43.0
(26) placaje: 76.0
(12) PA: 1.0
(195) de daños neutrales: 99.0
(36) agilidad: 144.0
(37) % resistencia al fuego: 19.0
(38) de daño crítico: 9.0
(31) alcance: -1.0
(29) % crítico: 20.0
(24) iniciativa: -401.0
(46) de resistencia a críticos: 49.0
(17) % resistencia al agua: 24.0
(64) al retiro de PA: 20.0
(13) inteligencia: 160.0
(22) suerte: 115.0
(70) de resistencia al empuje: 68.0
(59) huida: 27.0
(61) de daño de fuego: 20.0
(27) de daño de agua: 10.0
(47) de daño de aire: 10.0
(63) % resistencia a la tierra: 25.0
(39) a la esquiva pérdidas de PM: -13.0
(75) a la esquiva pérdidas de PA: 3.0
(8) PM: 3.0
(33) de resistencia al neutro: 30.0
(121) de cura: 55.0
(62) de daño de empuje: 85.0
(34) % resistencia neutral: 20.0
(98) Actitud: 109.0
(0) Intercambiable:: 0.0

In [30]:
assert False

AssertionError:

In [ ]:
weapon = get_chromosome_weapon(best)
get_damage(weapon,best)

np.float64(2228.7999999999997)

In [ ]:
best

[482, 320, 350, 310, 297, 184, 89, 119, 264, 226, 5, 265, 95, 107, 2, 0]

In [ ]:
item = tmp.iloc[8]
print(item["name"])
get_item_effects(item)[["name","effectId","diceNum","diceSide"]]

Anillo de Mizz Frizz

,name,effectId,diceNum,diceSide
2861093746004760000,#1{{~1~2 a }}#2 vitalidad,125,251.0,300.0
2861093746004760001,#1{{~1~2 a }}#2 fuerza,118,31.0,50.0
2861093746004760002,#1{{~1~2 a }}#2 inteligencia,126,31.0,50.0
2861093746004760003,#1{{~1~2 a }}#2 suerte,123,31.0,50.0
2861093746004760004,#1{{~1~2 a }}#2 % crítico,115,2.0,3.0
2861093746004760005,#1{{~1~2 a }}#2 de cura{{~p}}{{~z}},178,7.0,10.0
2861093746004760006,#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} neutro,430,7.0,10.0
2861093746004760007,#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} de tierra,422,7.0,10.0
2861093746004760008,#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} a l...,240,7.0,10.0
2861093746004760009,-#1{{~1~2 a -}}#2 huida,754,7.0,10.0
2861093746004760010,#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} crítico,418,7.0,10.0

In [ ]:
item = tmp.iloc[0]
print(item["name"])
get_item_effects(item)[["name","effectId","diceNum","diceSide"]]

Espada maldita del gran Desangrador Guerrero

,name,effectId,diceNum,diceSide
2861093746004750990,#1{{~1~2 a }}#2 de daños de aire,98,9.0,18.0
2861093746004750991,#1{{~1~2 a }}#2 de daños de agua,96,9.0,18.0
2861093746004750992,#1{{~1~2 a }}#2 de daños de fuego,99,9.0,18.0
2861093746004750993,#1{{~1~2 a }}#2 de daños neutrales,100,9.0,18.0
2861093746004750994,#1{{~1~2 a }}#2 de daños de tierra,97,9.0,18.0
2861093746004750995,#1{{~1~2 a }}#2 suerte,123,30.0,0.0
2861093746004750996,#1{{~1~2 a }}#2 inteligencia,126,30.0,0.0
2861093746004750997,#1{{~1~2 a }}#2 fuerza,118,30.0,0.0
2861093746004750998,#1{{~1~2 a }}#2 agilidad,119,30.0,0.0
2861093746004750999,#1{{~1~2 a }}#2 sabiduría,124,30.0,0.0
2861093746004751000,#1{{~1~2 a }}#2 vitalidad,125,165.0,0.0
2861093746004751001,#1{{~1~2 a }}#2% resistencia al aire,212,5.0,0.0
2861093746004751002,#1{{~1~2 a }}#2% resistencia al agua,211,5.0,0.0
2861093746004751003,#1{{~1~2 a }}#2% resistencia al fuego,213,5.0,0.0
2861093746004751004,#1{{~1~2 a }}#2% resistencia neutral,214,5.0,0.0
2861093746004751005,#1{{~1~2 a }}#2% resistencia a la tierra,210,5.0,0.0

In [ ]:
effects.loc["98"]

name                        #1{{~1~2 a }}#2 de daños de aire
type                                                 Effects
descriptionId                                        1102898
iconId                                                     6
characteristic                                             0
category                                                   2
characteristicOperator                                   NaN
showInTooltip                                              1
useDice                                                    1
forceMinMax                                                1
boost                                                      0
active                                                     0
oppositeId                                                 0
theoreticalDescriptionId                                 NaN
theoreticalPattern                                         1
showInSet                                                  0
bonusType                                                  0
useInFight                                                 1
effectPriority                                           500
effectPowerRate                                          2.0
elementId                                                  4
isInPercent                                                0
hideValueInTooltip                                         0
textIconReferenceId                                        6
effectTriggerDuration                                      0
actionFiltersId                            {'Array': [4, 3]}
Name: 98, dtype: object

In [ ]:
contributions[item.name]

characteristic
0     -90.0
10     30.0
11    165.0
12     30.0
13     30.0
14     30.0
15     30.0
33      5.0
34      5.0
35      5.0
36      5.0
37      5.0
Name: effectValue, dtype: float64

In [ ]:
item = tmp.iloc[8]
print(item["name"])
get_item_effects(item)[["name","effectId","diceNum","diceSide"]]

Anillo de Mizz Frizz

,name,effectId,diceNum,diceSide
2861093746004760000,#1{{~1~2 a }}#2 vitalidad,125,251.0,300.0
2861093746004760001,#1{{~1~2 a }}#2 fuerza,118,31.0,50.0
2861093746004760002,#1{{~1~2 a }}#2 inteligencia,126,31.0,50.0
2861093746004760003,#1{{~1~2 a }}#2 suerte,123,31.0,50.0
2861093746004760004,#1{{~1~2 a }}#2 % crítico,115,2.0,3.0
2861093746004760005,#1{{~1~2 a }}#2 de cura{{~p}}{{~z}},178,7.0,10.0
2861093746004760006,#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} neutro,430,7.0,10.0
2861093746004760007,#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} de tierra,422,7.0,10.0
2861093746004760008,#1{{~1~2 a }}#2 de resistencia{{~p}}{{~z}} a l...,240,7.0,10.0
2861093746004760009,-#1{{~1~2 a -}}#2 huida,754,7.0,10.0
2861093746004760010,#1{{~1~2 a }}#2 de daño{{~p}}{{~z}} crítico,418,7.0,10.0

In [ ]:
contributions[item.name]

characteristic
10     50.0
11    300.0
13     50.0
15     50.0
18      3.0
49     10.0
54     10.0
78    -10.0
86     10.0
88     10.0
92     10.0
Name: effectValue, dtype: float64

In [ ]:
best

[482, 320, 350, 310, 297, 184, 89, 119, 264, 226, 5, 265, 95, 107, 2, 0]

In [ ]:
lst = get_totals(best)
for idx,i in enumerate(lst):
    item = tmp.iloc[idx]
    print(f"{item['name']} (rid:{item.name}):")
    print(i.get("33", 0))  # Assuming "54" is a characteristic ID you want to print

Espada maldita del gran Desangrador Guerrero (rid:2861093746004724544):
5.0
Collar rhoarim (rid:2861093746004741472):
0
Taparrabos rhoarim (rid:2861093746004741473):
0
Botas de Miauvizor (rid:2861093746004731252):
0
Casco de Miauvizor (rid:2861093746004731253):
10.0
Capa Brigada (rid:2861093746004727614):
0
Lokulto (rid:2861093746004728051):
0
Cuadrifolio (rid:2861093746004732259):
0
Anillo de Mizz Frizz (rid:2861093746004728415):
0
Anillo Gwen Astarde (rid:2861093746004726812):
0
Dofus de los hielos (rid:2861093746004723117):
0
Lozano mayor (rid:2861093746004730368):
0
Dolmanax (rid:2861093746004727753):
0
Hércules mayor (rid:2861093746004728123):
0
Dofus Turquesa (rid:2861093746001847037):
0
Dofus Púrpura (rid:2861093746001847005):
0

In [ ]:
contributions["2861093746004726812"]

characteristic
10     60.0
12     30.0
13     60.0
18      5.0
26      2.0
44    400.0
48     10.0
82     10.0
84     15.0
88     15.0
90     15.0
92     15.0
Name: effectValue, dtype: float64

In [ ]:
item = items.loc["2861093746004730368"]
print(item["name"])
get_item_effects(item)[["name","effectId","diceNum","diceSide"]]
# get_item_contribution(item)

Lozano mayor

,name,effectId,diceNum,diceSide
2861093746004764621,#1{{~1~2 a }}#2 potencia (daños generales),138,80.0,0.0

In [ ]:
for i in items["criteria"].unique():
    print(i)

nan
CM<5
CP<12&CM<6&CW>99
CP<11
CP<12
CP<8
cs<25
ci<25
PT!24006&PT!350
PT!368&PT!24029
PT!369&PT!24017
PT!370&PT!24027
Ps=1&Pa>20
CP<9
Ps=2&Pa>30
cs<50
cs<80
cs<100
ca<25
ca<50
ca<80
ca<100
cw<25
cw<50
cw<80
cw<100
cv<25
cv<50
cv<80
cc<25
cv<100
cc<50
cc<80
cc<100
ci<50
ci<80
ci<100
CP<10
Pz=0&Sc!336
CM<6
Ps=1&Pa>10
Pj=44|Pj=48
CC>10
PG=3
CS>99&CA>99&CV>99
PE!8
PJ>2,40|PJ>24,40|PJ>36,40|PJ>28,40|PJ>26,40|PJ>41,40
PJ>2,80|PJ>24,80|PJ>36,80|PJ>28,80|PJ>26,80|PJ>41,80
PJ>2,120|PJ>24,120|PJ>36,120|PJ>28,120|PJ>26,120|PJ>41,120
PJ>2,180|PJ>24,180|PJ>36,180|PJ>28,180|PJ>26,180|PJ>41,180
PZ=1
CI<100&CC<100
BI=1
ci<20
ci<10
cw<20
cw<30
cw<60
ci<30
ci<5
cw<5
ci<60
cw<10
cw<40
ci<70
ci<40
cv<5
cv<30
cv<40
cv<10
cv<20
Ps=2
Ps=1
PN~Silaisie&BI=1
Ps=0
PO!2181&PO!2177&Ps=1&Pa=27&BI=1
PO!2177
PO=2177
PO=2177&Ps=1&Pa=27
CS<40&CI>80
PO!1723
CW>49&Ps=1
CW>49&Ps=2
CA>50
CC>50
CI>90
CS>90
CW>30&CV>50
Po!45
CC>30
CI>299&CC>199
CI>199
PS=0
PS=1
PG=1
PG=2
PG=4
PG=5
PG=6
PG=7
PG=8
PG=9
PG=10
PG=11
PN~Lordsoth&BI=1
PW>1499&CA>49
PG=6&PS=0
PG=6&PS=1
PW<1500|CA<50
CA>249|CS>249
CI>149&CA>149
CI>399
CA>299
PE!15
PZ=1&PW>1460
PO!7800
PO!7801
PL>59
PL>59

PO!7801&PO!7800
CI>99&CA>99&CC>99&CS>99
CS>299
(CS>89&CI>89&CA>89)&(CP<12|CM<6)
Qa=166
PN~xxramboplxx&BI=1
CI>99&CC>99&CP<12
CI>299
CP<12|CM<6
CV>1499&(CP<12|CM<6)
SI=1001
PK>800000
PZ=1&Po!45
PJ>65,100
CA>249&CI>249
CA>199&CC>199
CS>299&CA>149
CA>199&CI>199
CA>199&CC>199&CS>199
CS>249|CA>199
CC>199&CI>199
CS>199&CI>199
CS>140
PO!8945
PO!8938
PO!8943
PO!8942
PO!8939
PO!8944
PO!8946
PO!8947
BI=0
CS>249&CI>249
CI>249&CA>249
CS>199&CC>199
CI>199&CC>199
PT!373&PT!24028
PT!367&PT!24022
PX=3|PX=5|PX=2
CC>399
CC>249&CA>249
PR=0
PL<6
PO!9625
PO!9626
PO!9628
PO!9629
PO!9630
PO!9631
PO!9632
PO!9633
PO!9634
Qa=439
PO!10119
POX10055&POX10054&POX10056&POX10061&POX10058&POX10102
Pc=11&Po!45
PT!366&PT!24010
PT!364&PT!24007
Sc=1
PB=4|PB=22|PB=33|PB=169|PB=170|PB=168
PO!10668
Sc=4&PO!10681
Sc=5
Sc=7
PO!10676
Sc=7&(Pn!24|Pn!25)
Sc=13
Sc=14
PB=2|PB=96|PB=480
Sc=16
Sc=18
Sc=8&Po=5&Pm!175374338
(Pn!24|Pn!25)
Sc=19
Sc=997
Sc=666
PJ=2,200
PJ=11,200
PJ=13,200
PJ=15,200
PJ=16,200
PJ=24,200
PJ=28,200
PJ=26,200
PJ=27,200
PJ=36,200
PJ=41,200
PJ=44,200
PJ=48,200
PJ=60,200
PJ=62,200
PJ=63,200
PJ=64,200
PJ=65,200
Sc=21
Sc=22
Sc=23
Sc=24
Sc=25&Po=6
Sc=26
PZ=1&Oa>1999
POX11115&(Pn!24|Pn!25)
Qc=555&Qa!555
Qc=599
Qc=600
Qc=601
Qc=602
Qc=603
Qc=604
Qc=605
Qc=606
PB=604
CS>199&CI>199&CC>199&CA>199
CC=0
CS>149&CC>149&CI>149
CS>199&CA>199&(CP<12|CM<6)
CI>199&CA>199
CC>249
PO!11691
PO!11692
PO!11693
PO!11694
CA>249&CC>249
CV>1999
CS>299&CI>199
CA>199&CS>199
CA>249&CS>149
CI>199&CA>199&CC>199
CA>349
CI>249
CS>299&CA>299
CA>299&CC>299
CI>249&CA>199
CI>249&CC>249
CS>199&CA>199
PL>99&(PB=609|PB=610)
CS>249&CI>249&CC>249&CA>249
CS>199&CI>199&CA>199
CS>30&CI>30&CC>30
Qc=608
Qc=609
Qc=610
Qc=611
CI>249&CA>149
(PB=600|PB=601|PB=602|PB=604|PB=615)&Pm!54167842
(PB=600|PB=601|PB=602|PB=604|PB=615)&Pm!54176049
(PB=600|PB=601|PB=602|PB=604|PB=615)&Pm!54165815
(PB=600|PB=601|PB=602|PB=604|PB=615)&Pm!54171950
PZ=1&Oa>2999
Sc=996
PO!12195
PO!12197
PO!12206
POX9491&(Pn!24|Pn!25)
PS=0&Qf=714
PS=1&Qf=714
PE!57
PE!129
PE!119
PE!36
PE!51
PE!4
PE!9
PE!19
PE!58
PE!24
PE!25
PE!26
PE!11|PE!12|PE!13
PE!56
PE!6
PE!5
PE!38
PE!34
PE!53
PE!7
PE!35
PE!2
PE!10
PE!14
PE!3
PE!33
PE!32&OV>2879
PE!30
PE!43
PE!44
PE!42
PE!45
PE!41
PE!49
Pm=76284931
PZ=1&PE=51&Mw=0
PO!12815
PO!12816
PO!12818
PO!12820
PO!12822
PO!12824
PO!12826
Sc=996&Pc=11&Po!45&DD<60,12940
PZ=1&Mw=0
PL>59&(PB=759|PB=321|PB=320|PB=760|PB=758|PB=757)
Qa=920
Qa=920&Qo=5604
Sc=979&Pc=11&Po!45&DD<90,12526
PO!13224
PO!13225
PZ=1&PE=65
Pw=1
Qa=758&Qo=5697
CS>249
GM=1
Pn!27
PE!39
PE!66
PE!67
PE!68
PE!69
PE!71
PE!72
PE!73
PE!74
PE!75
(Sc=968&SG=08&Sd>18&Sd<27)|PX=A
PO!13441
Ad=58
PO!13443
PO!13445
PO!13447
PO!13449
PO!13451
PO!13453
PO!13455
PE!90
PO!13472
PO!13474
PL>9
PE!48
PE!88
PO!13508
Ad=209
OL!0
PO!13610
PO!13611
PO!13612
POX10841&(Pn!24|Pn!25)
Po=42
PE!92
CS>299&CI>299
CI>299&CA>299
PO!14011
PO!14012
PO!14013
PT!3506&PT!24030
CS>399
CS>399|CI>399|CA>399
CS>299&CC>299
Qc=1299
Qc=1300
Qc=1301
Qc=1302
Qc=1303
CI>399|CC>399|CA>399
CS>299&(CI>299|CC>299|CA>299)
CC>299&CI>149
PE!84
AM=1
Oc=R&Ox=4&SL>60&SL<81
Ow=1
PL>49&PO=14446
PL>49&PO=14444
PL>49&PO=14445
OA=57&Qf=827
PL>49&Ox=4
Ox=10&(SL>60&SL<81)
Ad=121
Po=45
PE!103
Pm=88082201
PE!87
PE!78
PE!105
PE!106
PE!107
CC>299&CA>299
PZ=1&Oa>999
PZ=1&Oa>499
PB=519
(Sc=994&SG=03&Sd<9)|PX=A
Qf=1201&Po!45
PE!80
PE!114
PE!113
CA>299&CI>299
PO!15220
PO!15221
PO!15222
PO!15223
PE!85
PE!52
PE!79
PE!112
Pm=129764354
Pm=128975872&Qo=8447
Pm=129238017&Qo=8471
PE!117
Qf=1507
Pm=128976898&Qo=8448
Pm=128977920&Qo=8449
PO!15354
PO!15404
PO!15405
PO!15406
PO!15407
Qf=1522|(Qa=1522&Qo>8660)
CI>299&CC>299
Pm=135397891&Qo=8872
PO!15581
PE!120
Pm=136052998
PB=813&PO=15629&PO=15630&PO=15631&PO=15632&PO!15628
Pm=135266819&Qo=8873
Pm=135267843&Qo=8874
Pm=135267845&Qo=8875
Pm=135268867&Qo=8876
Pm=54163257&Qo=9058&PO=15660
Pm=54171982&Qo=9060&PO=15660
Pm=60033541&Qo=9062&PO=15660
Pm=54169419&Qo=9064&PO=15660
OV>29
OV>89
OV>179
OV>269
OV>359
OV>389
OV>449
OV>539
OV>629
OV>719
OV>749
OV>809
OV>899
OV>989
OV>1079
OV>1109
OV>1169
OV>1259
OV>1349
CI>199&CS>199&CC>199&CA>199
OV>1469
OV>1529
OV>1619
OV>1709
OV>1799
OV>1829
OV>1889
PO!15798
PO!15799
PO!15800
PO!15801
OV>1979
OV>2069
OV>2159
OV>2189
OV>2249
OV>2339
OV>2429
OV>2519
OV>2549
OV>2609
OV>2699
OV>2789
OV>3959
OV>2909
OV>2969
OV>3059
OV>3149
OV>3239
OV>3269
OV>3329
OV>3419
OV>3509
OV>3599
OV>3629
OV>3689
OV>3779
OV>3869
OV>3989
OV>4049
Qo=9156&Pm=143139847&PO=15889
OV>4139
OV>4229
PE!82&OV>13
PE!27&OV>1439
PE!81&OV>4319
PB=838&Qo=9137
PB=837&Qo=9139
PB=837
PO!15966
PE!121
Pm=97260043&Qo=9426
PE!122
Pk<3
PE!130
PE!132
cc<5
cc<10
cc<20
cc<30
cc<40
cc<60
cc<70
cc<90
cv<60
cv<70
cv<90
cw<70
cw<90
ci<90
ca<5
ca<10
ca<20
ca<30
ca<35
ca<40
ca<45
ca<55
ca<60
ca<65
ca<70
ca<75
ca<85
ca<90
ca<95
Qf=1653|(Qa=1653&Qo>9954)
PE!77
PE!135
PE!134
Pm=154141187&Qo=10070&PO!16894&PO!16895&PO!16896&PO!16897
Pm=154141187
Qo=10156
PE!133
cs<10
cs<15
cs<20
cs<30
cs<35
cs<40
cs<45
cs<55
cs<60
cs<65
cs<70
cs<75
cs<85
cs<90
cs<95
Os!1
Os!2
Os!3
Os!4
PE!136
cs<5
PE!137
Of=1&PZ=1&Ps=2&Pa>19&Pf!88&Pf!89
Of=1&PZ=1&Ps=1&Pa>19&Pf!88&Pf!89
Qo=10309&Pm=189794311
Qo=10310&Pm=189793797
Qo=10311&Pm=189793793
PO!17516
PO!17517
PO!17518
PO!17519
PE!138
Qo=3115|Qo=10379
Os!5
PE!139
PE!140
Qo=10577&Pm=161356038
CI>299&CC>299&CA>299
Pm=161483012&Qo=10473
PE!142
PB=855|PB=856
PO!17666
(Pm=160956416&Qo=10520)|(Pm=160958464&Qo=10525)|(Pm=160956417&Qo=10528)|(Pm=160957953&Qo=10535)|(Pm=160957442&Qo=10542)|(Pm=160957954&Qo=10544)
PB=856&(Qo=10517|Qo=10518|Qc=1710)
CS>249&CI>249&CC>249
Qo=10477
Qo=10698&HA=92
Qc=1713
Qc=1713|Qa=1713
PE!143
(Ps=2&Pa>79)|(Qa=1470&Qo<8177&PO!15000)|(Qa=526&Qo>3595)
Pm=149946372&((Qa=1717&Qo>10781&Qo<10785)|(Qa=1718&Qo>10798&Qo<10802))
Of=1&Pf!88&Pf!89
Qo=10834|Qo=10844
PE!144
Pm=168560642&Qo=11002
Qc=1745
PE!146
CI>299&CS>299
Qo=11240&Pm=170132484
Ot!207
Ot!206
Ot!208
Of=5&Ps=2&Pa>19
Of=5&Ps=1&Pa>19
Of=5
PE!147
Qa=1782|Qa=1784|Qa=1785
PE!148
Qo=11562&Pm=142087181
Qo=11849&Pm=173670916
Qo=11920
PO!9905
PO!18451
PE!149
PE!150
PE!89
Py>50
Qa=1833&Qo=12117&Pm=175637506
Qo=12130&Pm=174855174
Qo=12131&Pm=174852098
Qo=12132&Pm=174854146
Ot!213
PE!152
PO!18654&Qa=1845
PE!155
PK>49999
Qc=1854
PE!156
Ot!226
Qo=12479&Pm=179176718
(Qa=1859|(Qo>12887&Qo<12889)|(Qo>12902&Qo<12904))&PO!18838
Pm=181141508
Pm=181404680&Qa=1865&Qo>12441&Qo<12443
((Qo>12417&Qo<12421)|(Qo>12441&Qo<12444))&Pm=180486661
PE!160
PE!163
CI>249&CS>249&CA>249
Pm=206832130&((Qo>12916&Qo=12917)|(Qo>12939&Qo=12940))
Pm=104861187&(Qo=12924|Qo=12947)
PE!166
OV>4349
OV>4409
OV>4499
OV>4589
OV>4679
OV>5039
OV>4709
OV>4769
OV>4859
OV>4949
CA>299&CS>299
PO!19272&Qa=1915&(Qo=13182|(Qo>13182&Qo<13183))
PE!16
PO!19319
Ot!228
Qa=1942&Qo>13493&Qo<13498
PO!19430&(Pm=187303426|Pm=187302402|Pm=187171330|Pm=187172354)
Qa=1935&Qo>13433
Qa=1936|Qf=1936
Qo=13686&PO=19489,5&PO=19491,8
Qa=1936&Qo<13451&HA!119
Ot!230&Sc=841
Qo=13640&Pm=184288258
Qo=13485
Qo=13486
Qo=13488
Qo=13487
Qo=13577
Ot!231
Ot!232
PJ=74,200
PE!176
PE!177
PE!178
PE!179
PE!180
Ot!240
Ot!239
Qo=13989&Pm=189530126
Pm=188484106|Pm=188484104|Pm=188485128|Pm=188484108
Qa=1991&Qo>14076&Qo>14077&Qo<14078&PO=19704,3
PG=12
PG=13
PG=14
PG=15
PG=16
PG=17
PG=18
Qo=14181&Pm=190842368
Qo=14188&Pm=190841859
Qo=14190&Pm=190840837
Ot!241
Qf=2014&PO!19960
CI>349&CS>349&CA>349&CC>349
Of=6&Pf!88&Pf!89
Ot!244
PE!189
PE!191
PE!192
PE!193
PE!190
PE!194
Ot!245
Pm=222298370
Sc=967
PO!20145
PO!20147
PO!20148
PO!20149
PO!20150
PO!20151
PO!20152
PZ=1&(Qa=2035|Qa=2036|Qa=2037)
PZ=1&((Qa=2037&Qo>14621)|Qa=2038|Qa=2039|Qa=2040|Qa=2041|Qa=2042|Qa=2043|Qa=2044)
Qf=1462&PL>39
Ot!255
Ot!256
OV>5219
OV>5399
OV>5129
OV>5309
OV>5069
Qa=2039&Qo>14469&Qo<14475&PO>20166,6
Of=6
Qo=14660&PO=20224&PO=20225&PO=20226
PE!196
PE!197
PE!199
Qo=14784
Qo=14510&Pm=195301388&PC=231
PE!200
Qo=14563&PO>20685,19
PO!20703
PO!20719
PO!20783
PO!20784
PO!20785
PO!20786
PO!20787
PO!20788
PO!20789
PO!20790
PO!20791
PO!20792
Ot!274
PE!209
Ot!270
Ot!269
Ot!268
Sc=945
Pm=196871178
PO!21097
Pm=196608000&POE20833
PO!20856
Qo=14914&Pm=197132288
Qo=14916&Pm=196346886
Qo=14913&Pm=196871170
Qo=14912&Pm=196345857
HA!50
Qf=2075
PE!210
PE!211
PE!212
PE!213
PE!214
Qo=14948
Ot!272
Ot!273
PB=916
PO!21036
Mw=0
Sc=945&Pc=11&Po!45&Qf=2066
Ot!277
Ot!276
Ot!275
PO!21046
PO!21047
PO!21048
PO!21049
PO!21050
PO!21051
PO!21061
PO!21062
PO!21063
PO!21064
PO!21065
PO!21066
PO!21067
PO!21068
PO!21069
PO!21070
PO!21071
PO!21072
PO!21073
PO!21074
PO!21075
PO!21076
PO!21077
PE!215
SC!5&SC!4
PE!216
PE!217
PE!218
PE!219
PE!220
PE!221
Ot!278
Ot!279
PE!222
Qo=15024
PO!21331
PO!21334
PO!21335
PO!21336
Of=1&PZ=1&Pf!88&Pf!89
Ot!280
PO!21411
Ot!281
Sc=940&((Qa=2091&Qo>15150)|Qf=2091)&PZ=1&PO=30071&DD<91,30071
PO!21492
PO!21493
PO!21491
PO!21490
PO!21495
PO!21494
PO!21496
PB!923
OH!34
PO!21623
PO!21628
PO!21629
Pm=4459522&Qo=15612
Pm=134666&Qo=15613
Pm=34473220&Qo=15611
(Pm=88605706|Pm=88604680|Pm=88605702|Pm=88606722)&Qo=15610
Pm=221249538&Qo=15614
Qo=15629&Pm=200804354
Qo=15638&Pm=200802308
Ot!282
Qo=15641&Pm=200802304
Qo=15664&Pm=200803328
PE!223
Qo=15666&Pm=200802306
PE!224
Ot!284
Ot!285
Ot!286
PE!230
PE!231
Qa=2131|Qf=2131
Qa=2111&Qo=15731&Pm=201590273
Qa=2113&Qo=15771
Pm!202901510&Po=74
Qa=2116&Qo>15812&Qo<15815&Pm=201589249
Qa=2111&Qo=15733&Pm=201589760
OH!4
OH!2
OH!31
OH!30
OH!27
OH!11
OH!25
OH!29
OH!21
OH!16
OH!15
OH!20
OH!24
OH!7
OH!1
OH!28
OH!3
OH!12
OH!5
OH!14
OH!23
OH!6
OH!19
OH!32
OH!33
OH!18
OH!10
OH!26
OH!9
OH!17
Qa=2116&Qo>15813&Qo<15816&Pm=201588741
Pm=202901510
Qo=16073&Pm=202244616
PE!232
Ot!291
Ot!292
Ot!293
Qo=16113&Pm=202642432
Qo=16123&Pm=202899464
OH!51
CA>299&CC>299&CI>299&CS>299
Pm=175642882&Qo=16211
Ot!295
Pn!30
PE!233
PE!234
PE!235
Ot!297
PO!22505&HA!757
Ot!294
PO!22537
PO!22538
PO!22539
PO!22540
PO!22541
PO!22542
PO!22543
PO!22544
PO!22545
POX22555&(Pn!22|Pn!23)
POX22556&(Pn!22|Pn!23)
POX22557&(Pn!22|Pn!23)
POX22558&(Pn!22|Pn!23)
POX22559&(Pn!22|Pn!23)
POX22560&(Pn!22|Pn!23)
POX22561&(Pn!22|Pn!23)
POX22562&(Pn!22|Pn!23)
POX22563&(Pn!22|Pn!23)
POX22564&(Pn!22|Pn!23)
PO!22983
PO!8547
PO!23009
PO!23011
PO!23013
Qo=16277&(Pm=207619080|Pm=207621128|Pm=207623176)
Qo=16324
Ot!300
Ot!301
Pm=206045185&Qo=16559
Qo=16356|Qo>16356
Qo=16566|Qo=16567|Qo=16568
PB=945&Qa=2197&PO!23239
Ot!304
Ot!303
Ot!299
Ot!302
DH>23,23318
Qa=2167&PT=413
Qo=16687
Qo=16601&Pm=205259266
Qo=16406&Pm=205521923
Qo=16407&Pm=205521923&PO!23496
Pm=209191424
Qf=2183
Pm=209192195
Qf=2181
Qo=16726
PO!23550
PO!23553
Ot!305
CS>449
PZ=1&Qf=2149&PO!20341
Po=79&HA!88&PZ=1&Qf=2149
((Qa=2162&Qo>16860)|Qf=2162)&Pm=209456136
PE!237
PE!238
Qf=2158&PO!23843
Qa=2199&Qo=17099&Pm=210633733
Ot!306
Pn!27&Pn!26
Qa=2201&Qo=17026&Pm=205259778
PZ=1&Qf=2149
PZ=1&Qf=2149&Sc=955
Ot!308
PZ=1&((Qa=2202&Qo>17064)|Qf=2202)&Po=78
PE!240
Ot!310
Ot!311
Ot!312
Ot!313
PO!24976
PE!241
Ot!316
SC=5
Ot!317
Ot!318
Ot!319
Ot!320
PE!242
PE!243
PE!244
Pm=210897154&Qo=18136
Qa=2415
PE!245
PE!246
PE!247
Qa=2409
Ot!322
Pm=214958338
PO!25304
Pm=214961664
PE!248
Ot!324
Ot!325
Ot!329
PE!252
PE!251
PE!249
Ot!330
PE!254
PE!255
Qa=2421&Qo=18314
PO>25951,29&Qo=18260
PZ=1&Pn!8&(Pm=74186754|Pm=74187778)&BI=1
Qf=2421
Ot!331
PO!26060
Qo=18307&Pm=185074176
Qa=2420&Qo>18308
PE!256
PE!257
Qa=2426&Qo=18331&PO!26094&Pm=104072449
PE!258
PE!259
PO!26122
PO!26123
Qa=2439&PO<26143,10&(Po=7|Po=11)
PO!26189
PO!26190
PO!26191
PO!26192
Pm=216795654&Qo=18415
Pm=216795653&Qo=18416
Pm=212864515&Qo=18416
PE!260
Ot!323
Ot!336
Ot!337
Ot!338
PE!262
PE!263
Qf=2442&PL>39
Qa=2442&Qo>18467&Qo<18469
Qa=2443&Qo=18473&POE26366
Qa=2444&Qo=18484&POE26366
Qa=2445&Qo=18499&POE26366
OA=1409&PL>49
OA=1088&PL>49
OA=1123&PL>49
OA=1166&PL>49
Qo=18548&Pm=221511680
PE!264
PE!265
(Qa=2446|Qf=2446)&HA!80
PE!266
PE!267
HA!51
HA!52
PE!268
PE!270
SC=5&ST=7
PE!275
PE!271
PE!272
PE!274
Ot!342
Ot!343
Ot!344
Ot!345
PE!273
PO!27201
Ot!346
OS=505
Ot!348
Ot!349
PO!27303
PO!27306
PO!27307
PO!27308
PO!27309
PO!27304
PO!27305
PE!278
PE!279
PT!24011&PT!24013
PT!24015&PT!24016
PE!280
PE!281
Ot!350
ST=8
OH!57
Ot!351
Ot!352
HA!129
HA!130
HA!131
OH!54
OH!55
Os!6
Os!7
Ot!353
Qa=2472&Qo>18716&HA!82&PO!27639&PO!27640&PO!27641&PO!27642
Ox=4
PE!282
Ox=10&SL<21
Pm=225972993&Qa=2463
Qa=2470
PE!283
PG=20
HA=137
HA!137
Qa=2479&Qo>18885
PE!284
PE!285
Ot!355
Ot!356
Ot!357
Ox=10&(SL>20&SL<41)
Ox=10&(SL>40&SL<61)
Ox=10&(SL>80&SL<101)
Ox=10&(SL>100&SL<121)
Ox=10&(SL>120&SL<141)
Ox=10&(SL>140&SL<161)
Ox=10&(SL>160&SL<181)
Ox=10&SL>180
Oc=R&Ox=4&SL<21
Oc=R&Ox=4&SL>20&SL<41
Oc=R&Ox=4&SL>40&SL<61
Oc=R&Ox=4&SL>80&SL<101
Oc=R&Ox=4&SL>100&SL<121
Oc=R&Ox=4&SL>120&SL<141
Oc=R&Ox=4&SL>140&SL<161
Oc=R&Ox=4&SL>160&SL<181
Oc=R&Ox=4&SL>180
PL>49&PO=27659&Mp=3
PE!286
Ot!358
Ot!359
Ot!360
Ot!361&(Qf=494|(Qf=2484&PO=28398))
Ow=2
PL<21
HA!236&(Pm=149427200|Pm=21497858|Pm=182192129)
HA!237&(Pm=209455110|Pm=204999171|Pm=206045189)
HA!238&Pm=208408576
HA!241&Pm=102760963
HA!245&Pm=130548736
HA!239&Pm=89392130
HA!240&Pm=56102912
HA!242&Pm=56365056
HA!243&Pm=21497858
HA!244&Pm=57155841
HA!246&Pm=125831683
HA!247&Pm=62919680
OH!58
Ot!362
Ot!363
PZ=1&Qf=2486
PO!28504
PO!28505
PO!28506
PO!28507
PO!28508
PO!28510
Ot!366
Pm=54161193&Qa=2488&Qo=18958
Qa=2488
Qa=2488&Qo>18967
PL<61
PL<81
PL<101
PL<121
PL<141
PL<161
PL<181
PL<200
PL<41
Qa=2488&Qo>18968
Qa=2488|Qa=2489
Qa=2488&Qo>18971
Ot!368
Ot!372
Ot!373
PE!287
Ot!371
PO!29387
Sc=996&HA!423
Sc=996&HA!424
Sc=996&HA!425
Ot!389
Ot!390
Ot!391
Ot!392
Ot!393
Ot!394
PO!29569
PO!29570
HA!510&HA!511
Ot!396
Pn!24|Pn!25
Ot!397
Ot!406
Ot!399
Ot!400
Ot!401
Ot!402
Ot!403
Ot!404
Ot!405
HA!508
OH!60
OH!61
OH!62
OH!63
Ot!407
Ot!408
Ot!409
Ot!410
Ot!411
HA!481&Ad=163
Ot!419
HA!528
HA!526
Ot!420
PO!30166
Ot!427
Ad=348
Ot!428
Ot!429
Ot!431
Ot!432
PL>19&ha!52
PL>49&PZ=1&PO=30071&Qf=2091
Ot!439
Ot!440
Ot!441
Ot!442
Ot!443
Ot!444
HA!586
HA!587
Ot!445
Ot!446
Ot!447
Sc=697
PL>19&PO!30761
PL>19&PO!30762
PL>19&PO!30763
PL>19&PO!30768
PL>19&PO!30769
PL>19&PO!30770
PO!30782
Ot!449
Ot!448
Ot!450
Ot!451
Ot!452
ha!45&ha!49
Ot!453
HA!626
HA!627
HA!628
HA!629
HA!630
HA!631
CS>999
CI>666
Ot!460
Ot!461
Ot!462
Ot!463
PG=1&PS=1
PG=1&PS=0
PG=7&PS=1
PG=7&PS=0
PG=8&PS=1
PG=9&PS=1
PG=9&PS=0
PG=11&PS=1
PG=11&PS=0
PG=15&PS=1
PG=15&PS=0
PG=16&PS=1
PG=16&PS=0
PG=17&PS=1
PG=17&PS=0
Ot!464
PE!319
PE!320
PE!321
PE!322
PG=2&PS=1
PG=2&PS=0
PG=3&PS=1
PG=3&PS=0
PG=4&PS=1
PG=4&PS=0
PG=5&PS=1
PG=5&PS=0
PG=8&PS=0
PG=10&PS=1
PG=10&PS=0
PG=12&PS=1
PG=12&PS=0
PG=13&PS=1
PG=13&PS=0
PG=14&PS=1
PG=14&PS=0
PG=18&PS=1
PG=18&PS=0
PG=20&PS=1
PG=20&PS=0
Ot!465
Ot!466
Ot!467
Ot!468
Ot!472
Qo=19272
PE!323
Ot!473
Ot!474
PE!327
PE!326
PE!325
PE!324
PE!331
Qa=2520&Qo=19285
PO=15206&HA!757&PO!22505
Ot!484
Pm=235799811&Qo>19302
Pm=235799552&(Qo<19312|Qc=2523|(Qa=2527&Qo=19487))
PO!31583&PO!31981&PO!31982
PO!31657&PO!31983&PO!31984
PO!31658&PO!31985&PO!31986
PO!31659
Pm=235799811&HA!782
CV>3949
PE!332
Ot!486
PE!328
PE!329
PE!330
Qa=2528&Qo=19452
HA!798
Ot!493
PE!333
Ot!495
OA=8839&PL>49
PE!334
PE!335
PE!336
PO!31993
PE!337

In [ ]:
item

name           Lozano mayor
type                  Items
m_flags               24712
id                    16332
nameId               515826
                   ...
diceNum                 NaN
diceSide                NaN
displayZero             NaN
class                Trofeo
set                     NaN
Name: 2861093746004730368, Length: 69, dtype: object