In [72]:
from optimizer import Optimizer
from chromosome import Chromosome
from character import Character
from utils import get_item_set, elements
import os
from data import items, item_sets
from datetime import datetime
import json

In [73]:
with open("reports/crit-melee-omni/2026-09-05_15-14-44/config.json", "r") as file:
    config = json.load(file)

In [74]:
import pandas as pd

dct = {}
for k,v in items.items():
    item_set = get_item_set(v,item_sets)
    dct[k] = {
        "name" : v["name"][config["optimizer"]["language"]],
        "set" : item_set["name"][config["optimizer"]["language"]] if item_set else None,
        "level" : v["level"],
        'ankama_id' : v['ankama_id']
    }
    dct[k].update({i:j for i,j in v['type'].items() if i not in dct[k]})
Items = pd.DataFrame.from_dict(dct, orient='index')

In [75]:
char = Character(**config["character"])
opt = Optimizer(char,
                 items,
                   item_sets,
                     **config["optimizer"])

Total items: 3220
Total item sets: 161
Total pools:
   16 with sizes [73, 75, 82, 82, 65, 82, 46, 93, 72, 720, 1, 1, 1, 293, 293, 293]
Total combinations: 10^27.04

In [77]:
# Current
chr = Chromosome(
                 [
                    8993, # Espada
                    13641, 13642, # Noai
                    14161, 14162, 14169, # Charlatan
                    14092, 14093, 18718, # Kuko
                    13673, # Lokulto
                    739, 694, 7754, 737, 7043, 18043 # Dofus
                 ],
                 opt)
chr.fitness, chr.get_final_damage("weapon")

(0.0, 1211.2)

In [56]:
Items.loc[chr.chromosome]

,name,set,level,ankama_id,id,itemTypeId,superTypeId,categoryId
8993,Espada maldita del gran Desangrador Guerrero,NaN,200,8993,6,80,2,0
13641,Gorro de Noai Aludem,Set de Noai Aludem,198,13641,16,27,10,0
13642,Anillo de Noai Aludem,Set de Noai Aludem,197,13642,9,17,3,0
14161,Capa Ordiosera,Set de charlatán,200,14161,17,43,11,0
14162,Cinto Dovencible,Set de charlatán,200,14162,10,58,4,0
14169,Talismán Tira,Set de charlatán,200,14169,1,33,1,0
14092,Anillo de kukoloide,Set de kukoloide,200,14092,9,17,3,0
14093,Botas de kukoloide,Set de kukoloide,200,14093,11,45,5,0
18718,Escudo de kukoloide,Set de kukoloide,200,18718,82,87,7,0
13673,Lokulto,NaN,20,13673,18,1,12,0
739,Dofus Turquesa,NaN,160,739,23,177,13,0
694,Dofus Púrpura,NaN,110,694,23,177,13,0
7754,Dofus Ocre,NaN,160,7754,23,177,13,0
737,Dofus Esmeralda,NaN,100,737,23,177,13,0
7043,Dofus de los hielos,NaN,180,7043,23,177,13,0
18043,Dofus abisal,NaN,180,18043,23,177,13,0

In [79]:
chr.totals_summary()

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
Items[Items["name"].str.match(
    "^Dofus marfil$|^Dofus Ocre$|^Dofus abisal$|^Potente Mayor$|^Dofus Turquesa$|^Dofus de los hielos$|^Dofus Púrpura$",case=False)
][['name', 'ankama_id']]

                      name  ankama_id
739         Dofus Turquesa        739
13825        Potente mayor      13825
18043         Dofus abisal      18043
7754            Dofus Ocre       7754
7043   Dofus de los hielos       7043
694          Dofus Púrpura        694
7115          Dofus Marfil       7115

In [49]:
Items[Items["name"].str.contains(
    "Cuadrifolio",case=False)
][['name', 'ankama_id']]

              name  ankama_id
18700  Cuadrifolio      18700

In [50]:
# Current
chr = Chromosome(
                 [
                    17578, 17579, 17580, # Miauvizor
                    19984, 19983, 19985, 19986,  # Vueloceronte
                    15190, # Melenutrof
                    18700, # Cuadrifolio
                    13673, # Lokulto
                    739, 13825, 18043, 7754, 7043, 694, 7115 # Dofus
                 ],
                 opt)
chr.fitness, chr.get_final_damage("weapon")

(564.597, 1140.6)

In [51]:
chr.set_summary()

       type_id      type               description  level                  set
694         13     Dofus             Dofus Púrpura    110                  NaN
739         13     Dofus            Dofus Turquesa    160                  NaN
7043        13     Dofus       Dofus de los hielos    180                  NaN
7115        13     Dofus              Dofus Marfil    180                  NaN
7754        13     Dofus                Dofus Ocre    160                  NaN
13673       12   Mascota                   Lokulto     20                  NaN
13825       13    Trofeo             Potente mayor    150                  NaN
15190        3    Anillo   Brazalete de melenutrof    200    Set de melenutrof
17578        5      Bota        Botas de Miauvizor    200     Set de Miauvizor
17579       10  Sombrero        Casco de Miauvizor    200     Set de Miauvizor
17580       11      Capa         Capa de Miauvizor    200     Set de Miauvizor
18043       13     Dofus              Dofus abisal    180                  NaN
18700        7    Escudo               Cuadrifolio    193                  NaN
19983        4  Cinturón  Cinturón de vueloceronte    200  Set de vueloceronte
19984        1   Amuleto   Amuleto de vueloceronte    200  Set de vueloceronte
19985        3    Anillo    Anillo de vueloceronte    200  Set de vueloceronte
19986        2      Arco      Arco de vueloceronte    200  Set de vueloceronte

In [52]:
chr.set_summary()["set"].value_counts()

set
Set de vueloceronte    4
Set de Miauvizor       3
Set de melenutrof      1
Name: count, dtype: int64

In [53]:
chr.totals_summary()

                       description   value
0                  Intercambiable:     0.0
8                               PM     4.0
9                        vitalidad  4050.0
10                       sabiduría   290.0
12                              PA    11.0
13                    inteligencia   736.0
16           % resistencia al aire    19.0
17           % resistencia al agua    29.0
22                          suerte   816.0
25                     prospección   127.0
26                         placaje    63.0
27                 de daño de agua   130.0
28                    invocaciones     2.0
29                       % crítico    81.0
31                         alcance     5.0
32      potencia (daños generales)   270.0
34           % resistencia neutral    34.0
36                        agilidad   636.0
37          % resistencia al fuego    29.0
38                 de daño crítico    67.0
39     a la esquiva pérdidas de PM    10.0
45                          fuerza   736.0
46   de resistencia a los críticos    96.0
47                 de daño de aire   100.0
48               de daño de tierra   130.0
49                  de daño neutro   130.0
59                           huida    80.0
61                de daño de fuego   120.0
63       % resistencia a la tierra    39.0
72                             NaN     5.0
98                         Actitud   736.0
163                -special spell-     0.0
189               de daños de aire    15.0
194             de daños de tierra    15.0
198              de daños de fuego    15.0
214               de daños de agua    15.0
252                            NaN     1.0

In [ ]:
Items[Items["name"].str.contains("Chani")]

                   name  set  level  id  itemTypeId  superTypeId  categoryId
11738  Anillo Chanicomo  NaN    194   9          17            3           0

In [ ]:
item = items[21392]
# item = items[6981]

In [ ]:
chr.are_item_conditions_met(item)

True

In [ ]:
item

{'ankama_id': 21392,
 'type': {'id': 324,
  'name': {'de': 'Prunkreittier',
   'en': 'Ceremonial Mount',
   'es': 'Montura de apariencia',
   'fr': "Monture d'apparat",
   'pt': 'Montaria de aparência'},
  'itemTypeId': 241,
  'superTypeId': 22,
  'categoryId': 5},
 'description': {'de': 'Dieses Zaumzeug ist ideal für Paraden geeignet und schützt euer Reittier vor Geschrei und Blütenblättern.',
  'en': 'This harness is ideal for parading around and will protect your mount from yelling and flower petals.',
  'es': 'Ideal para desfilar, estos arreos protegerán a tu montura de los gritos y los pétalos de flores.',
  'fr': 'Idéal pour parader, ce harnachement protègera votre monture des cris et des pétales de fleur.',
  'pt': 'Ótimos para exibir, estes arreios são o que há de melhor para proteger sua montaria contra gritos e pétalas de flores.'},
 'name': {'de': 'Azurblauer Dracotruter',
  'en': 'Azure Dragoturkey',
  'es': 'Dragopavo azur',
  'fr': "Dragodinde d'Azur",
  'pt': 'Dragoperu Celeste'},
 'image': 'https://static.ankama.com/dofus/www/game/items/200/182051.png',
 'conditions': None,
 'level': 60,
 'used_in_recipes': None,
 'characteristics': None,
 'effects': [{'min': 0,
   'max': 0,
   'type': {'de': 'Kompatibel zu:',
    'en': 'Compatible with:',
    'es': 'Compatible con',
    'fr': 'Compatible avec :',
    'pt': 'Compatível com:'},
   'min_max_irrelevant': -2,
   'templated': {'de': 'Kompatibel zu: 0',
    'en': 'Compatible with: 0',
    'es': 'Compatible con 0',
    'fr': 'Compatible avec : 0',
    'pt': 'Compatível com: 0'},
   'element_id': 1,
   'is_meta': False,
   'active': False},
  {'min': 0,
   'max': 0,
   'type': {'de': 'Kompatibel zu:',
    'en': 'Compatible with:',
    'es': 'Compatible con',
    'fr': 'Compatible avec :',
    'pt': 'Compatível com:'},
   'min_max_irrelevant': -2,
   'templated': {'de': 'Kompatibel zu: 0',
    'en': 'Compatible with: 0',
    'es': 'Compatible con 0',
    'fr': 'Compatible avec : 0',
    'pt': 'Compatível com: 0'},
   'element_id': 1,
   'is_meta': False,
   'active': False},
  {'min': 0,
   'max': 0,
   'type': {'de': 'Kompatibel zu:',
    'en': 'Compatible with:',
    'es': 'Compatible con',
    'fr': 'Compatible avec :',
    'pt': 'Compatível com:'},
   'min_max_irrelevant': -2,
   'templated': {'de': 'Kompatibel zu: 0',
    'en': 'Compatible with: 0',
    'es': 'Compatible con 0',
    'fr': 'Compatible avec : 0',
    'pt': 'Compatível com: 0'},
   'element_id': 1,
   'is_meta': False,
   'active': False},
  {'min': 0,
   'max': 0,
   'type': {'de': 'Kompatibel zu:',
    'en': 'Compatible with:',
    'es': 'Compatible con',
    'fr': 'Compatible avec :',
    'pt': 'Compatível com:'},
   'min_max_irrelevant': -2,
   'templated': {'de': 'Kompatibel zu: 0',
    'en': 'Compatible with: 0',
    'es': 'Compatible con 0',
    'fr': 'Compatible avec : 0',
    'pt': 'Compatível com: 0'},
   'element_id': 1,
   'is_meta': False,
   'active': False}],
 'dropMonsterIds': None,
 'criticalHitBonus': 0,
 'maxCastPerTurn': 0,
 'apCost': 0,
 'range': 0,
 'minRange': 0,
 'criticalHitProbability': 0,
 'pods': 1,
 'iconId': 182051,
 'parentSet': {'id': 679,
  'name': {'de': 'Azurblaues Prunkset',
   'en': 'Azure Ceremonial Set',
   'es': 'Set cosmético azulado',
   'fr': "Panoplie d'apparat d'Azur",
   'pt': 'Conjunto de Aparência Celeste'}},
 'hasParentSet': True}

In [ ]:
Items

,name,set,level,id,itemTypeId,superTypeId,categoryId
30114,Escudo de Lokus,NaN,1,248,19,22,5
31694,Máscara de seguridad,Set cosmético de inventor acorazado,1,246,6,22,5
33870,Alma capturada: Abrakeponerse el Optimista,NaN,90,328,243,6,1
33484,Elixir de abrevadero,NaN,175,326,244,9,2
8490,Fémur de Sfinter Cell,NaN,150,47,2,9,2
...,...,...,...,...,...,...,...
32456,Capa de Gúltar,Set cosmético de Gúltar,1,247,18,22,5
12399,Trampa del maestro cazador,NaN,1,147,138,14,3
13098,Casco de chafer primitivo,NaN,36,164,51,9,2
8801,Tejido de stropajo,NaN,92,55,9,9,2
26785,Tique de espera,NaN,1,260,131,14,3

In [ ]:
lst

NameError: name 'lst' is not defined

In [ ]:
lst[0][2]

In [ ]:
chr.are_item_conditions_met(items[11738])

In [ ]:
items[11738]["conditions"]

In [ ]:
chr.totals[8]

In [ ]:
lst = []
for i in items.values():
    if i["type"]["superTypeId"] not in [i[0] for i in opt.pool_types]:
        continue
    if i["conditions"]:
        print(opt.solution.are_item_conditions_met(i))
        lst.append((i,opt.solution.are_item_conditions_met(i)))

In [ ]:
lst[1]

In [ ]:
lst.count(True), lst.count(False)