In [1]:
from optimizer import Optimizer
from chromosome import Chromosome
from character import Character
from utils import get_item_set, elements
import os
from data import items, item_sets
from datetime import datetime
from analysis import construct_report_str
import json

In [5]:
# with open("reports/crit-omni-ranged/2026-09-05_15-44-02/config.json", "r") as file:
with open("workflows/report-steamer_20261007-160927/run_training/config.json", "r") as file:
    config = json.load(file)
    # Convert all string keys into int
    config['character']['exo'] = {int(k): v for k, v in config['character']['exo'].items()}

In [6]:
import pandas as pd

dct = {}
for k,v in items.items():
    item_set = get_item_set(v,item_sets)
    dct[k] = {
        "name" : v["name"][config["optimizer"]["language"]],
        "set" : item_set["name"][config["optimizer"]["language"]] if item_set else None,
        "level" : v["level"],
        'ankama_id' : v['ankama_id']
    }
    dct[k].update({i:j for i,j in v['type'].items() if i not in dct[k]})
Items = pd.DataFrame.from_dict(dct, orient='index')

In [7]:
char = Character(**config["character"])
opt = Optimizer(char,
                 items,
                   item_sets,
                     **config["optimizer"])

Total items: 1767
Total item sets: 161
Total pools:
   16 with sizes [73, 55, 82, 82, 65, 82, 46, 93, 72, 453, 1, 1, 297, 297, 297, 297]
Total combinations: 10^29.19

In [8]:
Items[Items['name'].str.contains('allister', case=False)][['name', 'ankama_id']]

                                      name  ankama_id
13055       Documento firmado por Allister      13055
22263                 Bolso de Allisterina      22263
13124                   Anillo de Allister      13124
22071  Bolsillito de merkasako de Allister      22071
13123                   Corona de Allister      13123
30060                    Égida de Allister      30060
13125                    Botas de Allister      13125

In [3]:
Items.loc[
[
			17581, # Collar de sota afortunada
			13124, # Anillo de Allister
			17582, # Guantes de sota afortunada
			15692, # Ballenotas
			19979, # Capa de Martillelo
			20366, # Valentía de la Señorita Jhessica
			694, # Dofus Púrpura
			7115, # Dofus Marfil
			7754, # Dofus Ocre
			18043, # Dofus abisal
			25220, # Escudo poseído
			24034, # Tintarela picuda
			19980, # Masquillelo
			13765, # Velocista mayor
			12714, # Acróbata mayor
			33166, # Vueloceronte ébano
			]
]

NameError: name 'Items' is not defined

In [7]:
Items.loc[[32121, 16333, 16335, 20354]]

,name,set,level,ankama_id,id,itemTypeId,superTypeId,categoryId
32121,Clarividencia de Mériana,NaN,200,32121,11,45,5,0
16333,Espabilador,NaN,100,16333,151,23,13,0
16335,Nómada,NaN,100,16335,151,23,13,0
20354,Tijeras del destino,NaN,200,20354,5,93,2,0

In [8]:
Items.loc[[32121, 16333, 16335]]

,name,set,level,ankama_id,id,itemTypeId,superTypeId,categoryId
32121,Clarividencia de Mériana,NaN,200,32121,11,45,5,0
16333,Espabilador,NaN,100,16333,151,23,13,0
16335,Nómada,NaN,100,16335,151,23,13,0

In [9]:
# Sword set
chr = Chromosome(
                 [
			18595, # Momistitorque
			14067, # Alianza inestable
			18594, # Momistianillo
			17681, # Arco de Miauvizor
			20364, # Botas del Culo Pateado
			19607, # Capilla absolutoria
			20365, # Audacia de Dodge
			7754, # Dofus Ocre
			18043, # Dofus abisal
			18692, # Escudístiko
			19291, # Jalapólux
			20465, # Máscara pazteka
			12642, # Empujador mayor
			13800, # Aventador
			13801, # Aventador mayor
			16306, # Chaquetero mayor
			],
                 opt)

report = construct_report_str(chr)
print(report)

	Fitness: 0.0014091757013409032
	Weapon damage: 0
		Weapon: Arco de Miauvizor
		AP Cost: 5
		Casts per turn: 1
	Spell damage:328.79999999999995
	Preferences:
		% crítico : 17.0
		% resistencia a la tierra : 22.0
		% resistencia al agua : 26.0
		% resistencia al aire : 26.0
		% resistencia al fuego : 26.0
		% resistencia neutral : 24.0
		PA : 12.0
		PM : 5.0
		alcance : 5.0
		huida : 33.0
		iniciativa : 1424.0
		placaje : -37.0
		potencia (daños generales) : 210.0
		vitalidad : 4150.0
	Characteristics:
		agilidad: 332.0
		suerte: 492.0
	Items:
		Type	Description	Level	ID
		Amuleto	Momistitorque	200	18595
		Anillo	Alianza inestable	199	14067
		Anillo	Momistianillo	200	18594
		Arco	Arco de Miauvizor	200	17681
		Bota	Botas del Culo Pateado	200	20364
		Capa	Capilla absolutoria	200	19607
		Cinturón	Audacia de Dodge	200	20365
		Dofus	Dofus Ocre	160	7754
		Dofus	Dofus abisal	180	18043
		Escudo	Escudístiko	200	18692
		Mascotura	Jalapólux	60	19291
		Sombrero	Máscara pazteka	200	20465
		Trofeo	Empujador mayor	150	12642
		Trofeo	Aventador	100	13800
		Trofeo	Aventador mayor	150	13801
		Trofeo	Chaquetero mayor	150	16306
	Penalized: True
		Penalized: 12 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 8 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 9 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 34 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 37 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 16 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 17 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 63 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 31 (lower) with offset 0.7615938734587377 and strength 0.01
	Chromosome: [
			18595, # Momistitorque
			14067, # Alianza inestable
			18594, # Momistianillo
			17681, # Arco de Miauvizor
			20364, # Botas del Culo Pateado
			19607, # Capilla absolutoria
			20365, # Audacia de Dodge
			7754, # Dofus Ocre
			18043, # Dofus abisal
			18692, # Escudístiko
			19291, # Jalapólux
			20465, # Máscara pazteka
			12642, # Empujador mayor
			13800, # Aventador
			13801, # Aventador mayor
			16306, # Chaquetero mayor
			]

In [14]:
# Load json
with open("data/MAPPED_SETS.json", "r") as f:
    sets = json.load(f)

# Load json
with open("data/MAPPED_ITEMS.json", "r") as f:
    items = json.load(f)

In [15]:
for s in sets:
    if s.get("effects"):
        for n, effects in s.get("effects").items():
            for effect in effects:
                if not effect:
                    continue
                if effect['element_id'] == 72:
                    print(s)

In [22]:
for i in items:
    if i.get("effects"):
        for effect in i.get("effects"):
            if not effect:
                continue
            if effect['element_id'] == 9:
                break

In [23]:
effect

{'min': 0,
 'max': 0,
 'type': {'de': 'An den Charakter gebunden',
  'en': 'Linked to the character',
  'es': 'Ligado a un personaje',
  'fr': 'Lié au personnage',
  'pt': 'Vinculado ao personagem'},
 'min_max_irrelevant': -2,
 'templated': {'de': 'An den Charakter gebunden',
  'en': 'Linked to the character',
  'es': 'Ligado a un personaje',
  'fr': 'Lié au personnage',
  'pt': 'Vinculado ao personagem'},
 'element_id': 81,
 'is_meta': False,
 'active': False}

In [24]:
# Current
chr = Chromosome(
                 [
                    17683, # Hacha
                    21235, # Torkelonia
                    13642, # Noai
                    14161, 14162, 14169, # Charlatan
                    14092, 14093, 18718, # Kuko
                    13673, # Lokulto
                    739, 694, 7754, 737, 7043, 18043 # Dofus
                 ],
                 opt)

report = construct_report_str(chr)
print(report)

	Fitness: 0.0
	Weapon damage: 0
		Weapon: Hacha de Miauvizor
		AP Cost: 4
		Casts per turn: 1
	Spell damage:280.20000000000005
	Preferences:
		% crítico : 83.0
		% resistencia a la tierra : 18.0
		% resistencia al agua : 36.0
		% resistencia al aire : 42.0
		% resistencia al fuego : 16.0
		% resistencia neutral : 20.0
		PA : 12.0
		PM : 6.0
		huida : 89.0
		iniciativa : 2565.0
		placaje : 115.0
		potencia (daños generales) : 185.0
		vitalidad : 4200.0
	Characteristics:
		agilidad: 746.0
	Items:
		Type	Description	Level	ID
		Amuleto	Talismán Tira	200	14169
		Anillo	Anillo de Noai Aludem	197	13642
		Anillo	Anillo de kukoloide	200	14092
		Bota	Botas de kukoloide	200	14093
		Capa	Capa Ordiosera	200	14161
		Cinturón	Cinto Dovencible	200	14162
		Dofus	Dofus Púrpura	110	694
		Dofus	Dofus Esmeralda	100	737
		Dofus	Dofus Turquesa	160	739
		Dofus	Dofus de los hielos	180	7043
		Dofus	Dofus Ocre	160	7754
		Dofus	Dofus abisal	180	18043
		Escudo	Escudo de kukoloide	200	18718
		Hacha	Hacha de Miauvizor	200	17683
		Mascota	Lokulto	20	13673
		Sombrero	Cuerno de Torkelonia	200	21235
	Penalized: True
		Penalized: 12 (lower) with offset 1.0 and strength 0.01
		Penalized: 8 (lower) with offset 1.0 and strength 0.01
		Penalized: 9 (lower) with offset 1.0 and strength 0.01
		Penalized: 34 (lower) with offset 1.0 and strength 0.01
		Penalized: 37 (lower) with offset 1.0 and strength 0.01
		Penalized: 16 (lower) with offset 1.0 and strength 0.01
		Penalized: 17 (lower) with offset 1.0 and strength 0.01
		Penalized: 63 (lower) with offset 1.0 and strength 0.01
		Penalized: 26 (lower) with offset 1.0 and strength 0.01
		Penalized: 59 (lower) with offset 1.0 and strength 0.01
	Chromosome: [
			14169, # Talismán Tira
			13642, # Anillo de Noai Aludem
			14092, # Anillo de kukoloide
			14093, # Botas de kukoloide
			14161, # Capa Ordiosera
			14162, # Cinto Dovencible
			694, # Dofus Púrpura
			737, # Dofus Esmeralda
			739, # Dofus Turquesa
			7043, # Dofus de los hielos
			7754, # Dofus Ocre
			18043, # Dofus abisal
			18718, # Escudo de kukoloide
			17683, # Hacha de Miauvizor
			13673, # Lokulto
			21235, # Cuerno de Torkelonia
			]

In [ ]:
# Current
chr = Chromosome(
                 [
                    17578, 17579, 17580, 19984, 19983, 19985, 19986, 15190, 18700, 13673, 739, 13825, 18043, 7754, 7043, 694, 7115
                 ],
                 opt)

report = construct_report_str(chr)
print(report)

	Fitness: 0.0
	Weapon damage: 1140.6
		Weapon: Arco de vueloceronte
		AP Cost: 5
		Casts per turn: 1
	Spell damage:1360.8000000000002
	Preferences:
		% crítico : 82.0
		huida : 80.0
		placaje : 63.0
		potencia (daños generales) : 270.0
		% crítico : 82.0
		huida : 80.0
		placaje : 63.0
		potencia (daños generales) : 270.0
	Characteristics:
		agilidad: 636.0
		fuerza: 736.0
		suerte: 816.0
		inteligencia: 736.0
	Items:
		Type	Description	Level	ID
		Amuleto	Amuleto de vueloceronte	200	19984
		Anillo	Anillo de vueloceronte	200	19985
		Anillo	Brazalete de melenutrof	200	15190
		Arco	Arco de vueloceronte	200	19986
		Bota	Botas de Miauvizor	200	17578
		Capa	Capa de Miauvizor	200	17580
		Cinturón	Cinturón de vueloceronte	200	19983
		Dofus	Dofus Marfil	180	7115
		Dofus	Dofus de los hielos	180	7043
		Dofus	Dofus abisal	180	18043
		Dofus	Dofus Turquesa	160	739
		Dofus	Dofus Ocre	160	7754
		Dofus	Dofus Púrpura	110	694
		Escudo	Cuadrifolio	193	18700
		Mascota	Lokulto	20	13673
		Sombrero	Casco de Miauvizor	200	17579
		Trofeo	Potente mayor	150	13825
	Chromosome: [
			19984, # Amuleto de vueloceronte
			19985, # Anillo de vueloceronte
			15190, # Brazalete de melenutrof
			19986, # Arco de vueloceronte
			17578, # Botas de Miauvizor
			17580, # Capa de Miauvizor
			19983, # Cinturón de vueloceronte
			7115, # Dofus Marfil
			7043, # Dofus de los hielos
			18043, # Dofus abisal
			739, # Dofus Turquesa
			7754, # Dofus Ocre
			694, # Dofus Púrpura
			18700, # Cuadrifolio
			13673, # Lokulto
			17579, # Casco de Miauvizor
			13825, # Potente mayor
			]