In [1]:
# Autoreload
%load_ext autoreload
%autoreload 2

from optimizer import Optimizer
from chromosome import Chromosome
from character import Character
from utils import get_item_set, elements
import json

with open('data/MAPPED_ITEMS.json', 'r') as file:
    items = {i["ankama_id"]: i for i in json.load(file)}

with open('data/MAPPED_SETS.json', 'r') as file:
    item_sets = {i["ankama_id"]: i for i in json.load(file)}

In [2]:
config = {
            "optimizer" : {
                "language": "es",
                "population_size": 300,
                "num_parents_mating": 100, # Number of parents to mate, usually 1/3 of population size
                "num_generations": 400,
                "mutation_rate": 0.05,
                "crossover_rate": 0.8,
                "parent_selection_type": "tournament",  # Tournament Selection
                "tournament_size": 3,
                "exclusions": {
                    "items": [6894,
                              6895,
                              3080,
                              9031,
                              6980 # Vulbis
                              ]  # Excluded items
                },
                "inclusions": {
                    "items": [
                        14093, # Botas kuko
                        18718, # Escudo kuko
                        14092, # Anillo kuko
                        8993, # Espada maldita
                        7754, # Dofus ocre
                    ]
                },
                "preferences": {
                    "lower": {
                        12: {
                            "target": 12,  # AP
                            "strength": 0.9,  # Penalty for not meeting the target
                        },
                        8: {
                            "target": 6,  # MP
                            "strength": 0.9,  # Penalty for not meeting the target
                        },
                        29: {
                            "target": 80,  # Crit
                            "strength": 0.75,  # Penalty for not meeting the target
                        },
                        9: {
                            "target": 4000,  # Vit
                            "strength": 0.5,  # Penalty for not meeting the target
                        },
                        34 : {
                            "target": 15, # %res neutral
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        37 : {
                            "target": 15, # %res fire
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        16 : {
                            "target": 15, # %res air
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        17 : {
                            "target": 15, # %res water
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        63 : {
                            "target": 15, # %res range
                            "strength": 0.1,  # Penalty for not meeting the target
                        }
                    },
                    "upper": {}
                },

                "level_offset": 10,  # Level offset for items
                "objective": "weapon"  # Objective to optimize, can be "weapon" or "elements"
            },
            "character": {
                "level": 200,
                "scrolled": True,
                "exo": {
                    12:1, # Exo AP
                    8:1
                    },  # Exo MP
                "distributed_points": {
                    9: 995,  # Vitality
                },
                "elements" : [
                    36, # Agility,
                    22, # Chance
                    13, # Intelligence
                    45  # Strength
                ],
            },
        }

In [3]:
import pandas as pd

effect_descriptions = {}
for _,item in items.items():
    if not item["effects"]:
        continue
    for effect in item["effects"]:
        effect_descriptions[effect["element_id"]] = effect["type"]

dct = {}
for k,v in items.items():
    item_set = get_item_set(v,item_sets)
    dct[k] = {
        "name" : v["name"][config["optimizer"]["language"]],
        "set" : item_set["name"][config["optimizer"]["language"]] if item_set else None,
        "level" : v["level"]
    }
Items = pd.DataFrame.from_dict(dct, orient='index')

In [4]:
Items[Items["name"].str.contains("kuko",case=False)]

                       name               set  level
13989    Pluma de kukoloide              None    200
14091  Amuleto de kukoloide  Set de kukoloide    200
14092   Anillo de kukoloide  Set de kukoloide    200
14093    Botas de kukoloide  Set de kukoloide    200
13988      Ojo de kukoloide              None    200
18718   Escudo de kukoloide  Set de kukoloide    200

In [5]:
char = Character(**config["character"])
opt = Optimizer(char,
                 items,
                   item_sets,
                     **config["optimizer"])

Total items: 2748
Total item sets: 148
Total pools:
   16 with sizes [69, 1, 1, 71, 62, 1, 1, 88, 69, 412, 1, 326, 326, 326, 326, 326]
Total combinations: 10^24.45

In [6]:
solutions = opt.optimize(islands = 10, max_workers = 4)

In [7]:
for idx, solution in enumerate(sorted(solutions, key=lambda x: x.fitness, reverse=True)):
    if solution.penalized:
        continue
    print(f"Solution {idx}:")
    print("\tFitness:", solution.get_fitness())
    print("\tWeapon damage:", solution.get_final_weapon_damage())
    print("\tElemental damage:", solution.get_final_elemental_damage())
    # print("\tIs the solution viable?", solution.viable)
    # print("\tWas the solution penalized?", solution.penalized)

    print("\tPreferences:")
    df = solution.totals_summary(effect_descriptions)
    for bound, preference in solution.preferences.items():
        for element, details in preference.items():
            row = df.loc[element]
            print(f"\t\t{row['description']} : {row['value']}")
    print("\tCharacteristics:")
    for element in elements:
        print(f"\t\t{df.loc[element]['description']}: {df.loc[element]['value']}")

    print("\tItems:")
    print("\t\tType\tDescription\tLevel")
    for item,row in solution.set_summary().sort_values("type").iterrows():
        # Prettify the output
        print(f"\t\t{row['type']}\t{row['description']}\t{row['level']}")
    print("\tChromosome:")
    print("\t\t", solution.chromosome)

Solution 0:
	Fitness: 1936.7600000000002
	Weapon damage: 1936.7600000000002
	Elemental damage: 1485.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 88.0
		vitalidad : 4560.0
		% resistencia neutral : 17.0
		% resistencia al fuego : 25.0
		% resistencia al aire : 44.0
		% resistencia al agua : 33.0
		% resistencia a la tierra : 33.0
	Characteristics:
		agilidad: 530.0
		suerte: 200.0
		inteligencia: 530.0
		fuerza: 480.0
		vitalidad: 4560.0
		sabiduría: 400.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de estrígido	200
		Anillo	Anillo de Noai Aludem	197
		Anillo	Anillo de kukoloide	200
		Bota	Botas de kukoloide	200
		Capa	Capa Pología	198
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Marfil	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Microsmoglob	20
		Sombrero	Gorro de Noai Aludem	198
	Chromosome:
		 [14094  8993 14092 13642 14095 14093 18718 13641 14168 31885  7754 13344
  7043  7115   694   739]
Solution 1:
	Fitness: 1815.86
	Weapon damage: 1815.86
	Elemental damage: 1350.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 84.0
		vitalidad : 4710.0
		% resistencia neutral : 23.0
		% resistencia al fuego : 21.0
		% resistencia al aire : 42.0
		% resistencia al agua : 31.0
		% resistencia a la tierra : 21.0
	Characteristics:
		agilidad: 380.0
		suerte: 200.0
		inteligencia: 380.0
		fuerza: 640.0
		vitalidad: 4710.0
		sabiduría: 370.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de estrígido	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa Pología	198
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Microsmoglob	20
		Sombrero	Pendiente de Kongoku	200
		Trofeo	Hércules mayor	150
	Chromosome:
		 [14094  8993 14092 22205 14095 14093 18718 17107 14168 31885  7754 13344
   694 13759  7043   739]
Solution 2:
	Fitness: 1804.32
	Weapon damage: 1804.32
	Elemental damage: 1333.5
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 83.0
		vitalidad : 4910.0
		% resistencia neutral : 15.0
		% resistencia al fuego : 21.0
		% resistencia al aire : 32.0
		% resistencia al agua : 41.0
		% resistencia a la tierra : 28.0
	Characteristics:
		agilidad: 440.0
		suerte: 260.0
		inteligencia: 380.0
		fuerza: 730.0
		vitalidad: 4910.0
		sabiduría: 380.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de estrígido	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa Pología	198
		Cinturón	Zarcinturón de Corrupción	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Microsmoglob	20
		Sombrero	Casco de Ogivol	193
		Trofeo	Potente mayor	150
	Chromosome:
		 [14094  8993 14092 22205 22209 14093 18718 13130 14168 31885  7754   739
 13825 13344   694  7043]
Solution 3:
	Fitness: 1762.7199999999998
	Weapon damage: 1762.7199999999998
	Elemental damage: 1367.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 82.0
		vitalidad : 4510.0
		% resistencia neutral : 30.0
		% resistencia al fuego : 26.0
		% resistencia al aire : 36.0
		% resistencia al agua : 23.0
		% resistencia a la tierra : 20.0
	Characteristics:
		agilidad: 430.0
		suerte: 190.0
		inteligencia: 310.0
		fuerza: 490.0
		vitalidad: 4510.0
		sabiduría: 410.0
	Items:
		Type	Description	Level
		Amuleto	Collar rhoarim	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa de Fuji Gélifux	193
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Lokulto	20
		Sombrero	Pendiente de Kongoku	200
		Trofeo	Lozano mayor	150
		Trofeo	Espabilador	100
	Chromosome:
		 [31761  8993 14092 22205 14095 14093 18718 17107 12117 13673  7754 16333
 16332  7043   694   739]
Solution 4:
	Fitness: 1732.1599999999999
	Weapon damage: 1732.1599999999999
	Elemental damage: 1260.5
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 87.0
		vitalidad : 5010.0
		% resistencia neutral : 25.0
		% resistencia al fuego : 23.0
		% resistencia al aire : 22.0
		% resistencia al agua : 33.0
		% resistencia a la tierra : 23.0
	Characteristics:
		agilidad: 490.0
		suerte: 200.0
		inteligencia: 380.0
		fuerza: 680.0
		vitalidad: 5010.0
		sabiduría: 400.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto del Corazón Valiente	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa del Corazón Valiente	200
		Cinturón	Zarcinturón de Corrupción	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Microsmoglob	20
		Sombrero	Maskrobio	200
		Trofeo	Torturador airoso mayor	150
	Chromosome:
		 [19241  8993 14092 22205 22209 14093 18718 15695 19243 31885  7754   739
   694 13786 13344  7043]
Solution 5:
	Fitness: 1593.075
	Weapon damage: 1593.075
	Elemental damage: 1244.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 80.0
		vitalidad : 4810.0
		% resistencia neutral : 23.0
		% resistencia al fuego : 18.0
		% resistencia al aire : 43.0
		% resistencia al agua : 27.0
		% resistencia a la tierra : 20.0
	Characteristics:
		agilidad: 380.0
		suerte: 360.0
		inteligencia: 450.0
		fuerza: 470.0
		vitalidad: 4810.0
		sabiduría: 405.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de Wulán	200
		Anillo	Anillo de kukoloide	200
		Anillo	Pikanillo	195
		Bota	Botas de kukoloide	200
		Capa	Capa de la reina del azar	200
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Microsmoglob	20
		Sombrero	Pendiente de Kongoku	200
		Trofeo	Lozano mayor	150
		Trofeo	Nómada	100
	Chromosome:
		 [24029  8993 14092 14882 14095 14093 18718 17107 17577 31885  7754 16335
   739 16332  7043 13344]
Solution 6:
	Fitness: 1551.25
	Weapon damage: 1551.25
	Elemental damage: 1256.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 80.0
		vitalidad : 4860.0
		% resistencia neutral : 15.0
		% resistencia al fuego : 18.0
		% resistencia al aire : 37.0
		% resistencia al agua : 20.0
		% resistencia a la tierra : 31.0
	Characteristics:
		agilidad: 370.0
		suerte: 190.0
		inteligencia: 370.0
		fuerza: 310.0
		vitalidad: 4860.0
		sabiduría: 440.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de estrígido	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de famosillo	200
		Bota	Botas de kukoloide	200
		Capa	Capa de Atcham	200
		Cinturón	Cinturón inestable	196
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Lokulto	20
		Sombrero	Pendiente de Kongoku	200
		Trofeo	Lozano	100
		Trofeo	Lozano mayor	150
		Trofeo	Espabilador	100
	Chromosome:
		 [14094  8993 14092 19608 14069 14093 18718 17107 17584 13673  7754 16333
  7043 16332   739 16331]
Solution 7:
	Fitness: 1506.5
	Weapon damage: 1506.5
	Elemental damage: 1172.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 80.0
		vitalidad : 4610.0
		% resistencia neutral : 20.0
		% resistencia al fuego : 33.0
		% resistencia al aire : 34.0
		% resistencia al agua : 30.0
		% resistencia a la tierra : 28.0
	Characteristics:
		agilidad: 430.0
		suerte: 190.0
		inteligencia: 370.0
		fuerza: 530.0
		vitalidad: 4610.0
		sabiduría: 380.0
	Items:
		Type	Description	Level
		Amuleto	Collar rhoarim	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa de Anerice	200
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascotura	Perforror	60
		Sombrero	Gorro de Noai Aludem	198
		Trofeo	Hércules mayor	150
		Trofeo	Espabilador	100
	Chromosome:
		 [31761  8993 14092 22205 14095 14093 18718 13641 19076 15243  7754 13759
   739 16333   694  7043]

In [8]:
solution.totals_summary(effect_descriptions)#.sort_values("value",ascending=False)

                     description   value
0                Intercambiable:     0.0
8                             PM     6.0
9                      vitalidad  4410.0
10                     sabiduría   410.0
12                            PA    12.0
13                  inteligencia   380.0
14       de resistencia al fuego    10.0
15    de resistencia a la tierra    25.0
16         % resistencia al aire    34.0
17         % resistencia al agua    20.0
22                        suerte   200.0
24                    iniciativa  1800.0
25                   prospección    80.0
26                       placaje    71.0
27               de daño de agua    35.0
28                  invocaciones     2.0
29                     % crítico    71.0
31                       alcance     3.0
32    potencia (daños generales)   300.0
34         % resistencia neutral    20.0
36                      agilidad   530.0
37        % resistencia al fuego    18.0
38               de daño crítico   120.0
45                        fuerza   630.0
46     de resistencia a críticos   -32.0
47               de daño de aire   104.0
48             de daño de tierra   104.0
49                de daño neutro   104.0
50               al retiro de PM    10.0
60        de resistencia al aire    10.0
61              de daño de fuego    65.0
62             de daño de empuje   -11.0
63     % resistencia a la tierra    28.0
72                          None     5.0
75   a la esquiva pérdidas de PA    16.0
98                       Actitud   555.0
121                      de cura     7.0
163              -special spell-     0.0
189             de daños de aire    18.0
194           de daños de tierra    18.0
195           de daños neutrales    18.0
198            de daños de fuego    18.0
214             de daños de agua    18.0
252                         None     1.0

In [9]:
set_summary = solution.set_summary()
set_summary

,type_id,type,description,level,set
694,13,Dofus,Dofus Púrpura,110,None
739,13,Dofus,Dofus Turquesa,160,None
7043,13,Dofus,Dofus de los hielos,180,None
7754,13,Dofus,Dofus Ocre,160,None
8993,2,Espada,Espada maldita del gran Desangrador Guerrero,200,None
12117,11,Capa,Capa de Fuji Gélifux,193,Set de Fuji Gélifux
12118,10,Sombrero,Tocado de Fuji Gélifux,195,Set de Fuji Gélifux
12120,3,Anillo,Anillo de Fuji Gélifux,192,Set de Fuji Gélifux
13344,13,Dofus,Dolmanax,100,None
13673,12,Mascota,Lokulto,20,None
13759,13,Trofeo,Hércules mayor,150,None
14092,3,Anillo,Anillo de kukoloide,200,Set de kukoloide
14093,5,Bota,Botas de kukoloide,200,Set de kukoloide
14094,1,Amuleto,Amuleto de estrígido,200,Set de estrígido
14095,4,Cinturón,Cinturón de estrígido,200,Set de estrígido
18718,7,Escudo,Escudo de kukoloide,200,Set de kukoloide

In [10]:
set_summary["set"].value_counts()

set
Set de Fuji Gélifux    3
Set de kukoloide       3
Set de estrígido       2
Name: count, dtype: int64

In [11]:
import matplotlib.pyplot as plt
plt.plot(opt.ga_instance.best_solutions_fitness)
plt.xlabel('Generation')
plt.ylabel('Best Fitness')

AttributeError: 'Optimizer' object has no attribute 'ga_instance'

In [ ]:
assert False

AssertionError:

In [14]:
# Current
chr = Chromosome(
                 [
                    8993, # Espada
                    13641, 13642, # Noai
                    14161, 14162, 14169, # Charlatan
                    14092, 14093, 18718, # Kuko
                    13673, # Lokulto
                    739, 694, 7754, 737, 7043, 17078 # Dofus
                 ],
                 opt)
chr.fitness

2049.74

In [ ]:
Items[Items["name"].str.contains("kuko")]

                       name               set  level
13989    Pluma de kukoloide              None    200
14091  Amuleto de kukoloide  Set de kukoloide    200
14092   Anillo de kukoloide  Set de kukoloide    200
14093    Botas de kukoloide  Set de kukoloide    200
13988      Ojo de kukoloide              None    200
18718   Escudo de kukoloide  Set de kukoloide    200

In [ ]:
chr.set_summary()

In [ ]:
chr.set_summary()["set"].value_counts()

In [ ]:
chr.totals_summary(effect_descriptions)

In [ ]:
Items[Items["name"].str.contains("Chani")]

In [ ]:
item = items[21392]
# item = items[6981]

In [ ]:
chr.are_item_conditions_met(item)

In [ ]:
item

In [ ]:
Items

In [ ]:
lst

In [ ]:
lst[0][2]

In [ ]:
chr.are_item_conditions_met(items[11738])

In [ ]:
items[11738]["conditions"]

In [ ]:
chr.totals[8]

In [ ]:
lst = []
for i in items.values():
    if i["type"]["superTypeId"] not in [i[0] for i in opt.pool_types]:
        continue
    if i["conditions"]:
        print(opt.solution.are_item_conditions_met(i))
        lst.append((i,opt.solution.are_item_conditions_met(i)))

In [ ]:
lst[1]

In [ ]:
lst.count(True), lst.count(False)