In [2]:
# Autoreload
%load_ext autoreload
%autoreload 2

from optimizer import Optimizer
from chromosome import Chromosome
from character import Character
from utils import get_item_set, elements
import json

with open('data/MAPPED_ITEMS.json', 'r') as file:
    items = {i["ankama_id"]: i for i in json.load(file)}

with open('data/MAPPED_SETS.json', 'r') as file:
    item_sets = {i["ankama_id"]: i for i in json.load(file)}

In [3]:
config = {
            "optimizer" : {
                "language": "es",
                "population_size": 300,
                "num_parents_mating": 100, # Number of parents to mate, usually 1/3 of population size
                "num_generations": 400,
                "mutation_rate": 0.05,
                "crossover_rate": 0.8,
                "parent_selection_type": "tournament",  # Tournament Selection
                "tournament_size": 3,
                "exclusions": {
                    "items": [6894,
                              6895,
                              3080,
                              9031,
                              6980 # Vulbis
                              ]  # Excluded items
                },
                "inclusions": {
                    "items": [
                        14093, # Botas kuko
                        18718, # Escudo kuko
                        # 19985, # Anillo de vuelo

                    ]
                },
                "preferences": {
                    "lower": {
                        12: {
                            "target": 12,  # AP
                            "strength": 0.9,  # Penalty for not meeting the target
                        },
                        8: {
                            "target": 6,  # MP
                            "strength": 0.9,  # Penalty for not meeting the target
                        },
                        29: {
                            "target": 80,  # Crit
                            "strength": 0.75,  # Penalty for not meeting the target
                        },
                        9: {
                            "target": 4000,  # Vit
                            "strength": 0.5,  # Penalty for not meeting the target
                        },
                        34 : {
                            "target": 15, # %res neutral
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        37 : {
                            "target": 15, # %res fire
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        16 : {
                            "target": 15, # %res air
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        17 : {
                            "target": 15, # %res water
                            "strength": 0.1,  # Penalty for not meeting the target
                        },
                        63 : {
                            "target": 15, # %res range
                            "strength": 0.1,  # Penalty for not meeting the target
                        }
                    },
                    "upper": {}
                },
                "elements" : [
                    36, # Agility,
                    22, # Chance
                    13, # Intelligence
                    45  # Strength
                ],
                "level_offset": 10,  # Level offset for items
                "objective": "weapon"  # Objective to optimize, can be "weapon" or "elements"
            },
            "character": {
                "level": 200,
                "scrolled": True,
                "exo": {
                    12:1, # Exo AP
                    8:1
                    },  # Exo MP
                "distributed_points": {
                    9: 995,  # Vitality
                }
            },
        }

In [4]:
import pandas as pd

effect_descriptions = {}
for _,item in items.items():
    if not item["effects"]:
        continue
    for effect in item["effects"]:
        effect_descriptions[effect["element_id"]] = effect["type"]

dct = {}
for k,v in items.items():
    item_set = get_item_set(v,item_sets)
    dct[k] = {
        "name" : v["name"][config["optimizer"]["language"]],
        "set" : item_set["name"][config["optimizer"]["language"]] if item_set else None,
        "level" : v["level"]
    }
Items = pd.DataFrame.from_dict(dct, orient='index')

In [5]:
# Items[Items["name"].str.contains("vuelo")]

In [6]:
char = Character(**config["character"])
opt = Optimizer(char,
                 items,
                   item_sets,
                     **config["optimizer"])

Total items: 2748
Total item sets: 148
Total pools:
   16 with sizes [69, 118, 71, 71, 62, 1, 1, 88, 69, 412, 326, 326, 326, 326, 326, 326]
Total combinations: 10^30.88

In [6]:
solutions = opt.optimize(islands = 10, max_workers = 4)

In [14]:
for idx, solution in enumerate(sorted(solutions, key=lambda x: x.fitness, reverse=True)):
    if solution.penalized:
        continue
    print(f"Solution {idx}:")
    print("\tFitness:", solution.get_fitness())
    print("\tWeapon damage:", solution.get_final_weapon_damage())
    print("\tElemental damage:", solution.get_final_elemental_damage())
    # print("\tIs the solution viable?", solution.viable)
    # print("\tWas the solution penalized?", solution.penalized)

    print("\tPreferences:")
    df = solution.totals_summary(effect_descriptions)
    for bound, preference in solution.preferences.items():
        for element, details in preference.items():
            row = df.loc[element]
            print(f"\t\t{row['description']} : {row['value']}")
    print("\tCharacteristics:")
    for element in elements:
        print(f"\t\t{df.loc[element]['description']}: {df.loc[element]['value']}")

    print("\tItems:")
    print("\t\tType\tDescription\tLevel")
    for item,row in solution.set_summary().sort_values("type").iterrows():
        # Prettify the output
        print(f"\t\t{row['type']}\t{row['description']}\t{row['level']}")

Solution 0:
	Fitness: 2152.49
	Weapon damage: 2152.49
	Elemental damage: 1671.25
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 89.0
		vitalidad : 4410.0
		% resistencia neutral : 15.0
		% resistencia al fuego : 21.0
		% resistencia al aire : 45.0
		% resistencia al agua : 41.0
		% resistencia a la tierra : 21.0
	Characteristics:
		agilidad: 530.0
		suerte: 385.0
		inteligencia: 690.0
		fuerza: 540.0
		vitalidad: 4410.0
		sabiduría: 430.0
	Items:
		Type	Description	Level
		Amuleto	Talismán Tira	200
		Anillo	Anillo de Noai Aludem	197
		Anillo	Anillo de kukoloide	200
		Bota	Botas de kukoloide	200
		Capa	Capa Ordiosera	200
		Cinturón	Cinto Dovencible	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Lokulto	20
		Sombrero	Gorro de Noai Aludem	198
		Trofeo	Suertudo menor	50
Solution 1:
	Fitness: 1766.76
	Weapon damage: 1766.76
	Elemental damage: 1221.5
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 89.0
		vitalidad : 4660.0
		% resistencia neutral : 23.0
		% resistencia al fuego : 39.0
		% resistencia al aire : 34.0
		% resistencia al agua : 23.0
		% resistencia a la tierra : 30.0
	Characteristics:
		agilidad: 400.0
		suerte: 200.0
		inteligencia: 570.0
		fuerza: 960.0
		vitalidad: 4660.0
		sabiduría: 400.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de kukoloide	200
		Anillo	Sello del rey jugador	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa Pología	198
		Cinturón	Zarcinturón de Corrupción	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Microsmoglob	20
		Sombrero	Corona del rey jugador	200
		Trofeo	Hércules mayor	150
Solution 2:
	Fitness: 1690.575
	Weapon damage: 1690.575
	Elemental damage: 1315.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 80.0
		vitalidad : 4660.0
		% resistencia neutral : 21.0
		% resistencia al fuego : 36.0
		% resistencia al aire : 39.0
		% resistencia al agua : 23.0
		% resistencia a la tierra : 21.0
	Characteristics:
		agilidad: 390.0
		suerte: 260.0
		inteligencia: 390.0
		fuerza: 520.0
		vitalidad: 4660.0
		sabiduría: 395.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de kukoloide	200
		Anillo	Pikanillo	195
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa Pología	198
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Lokulto	20
		Sombrero	Gorro de Noai Aludem	198
		Trofeo	Suertudo mayor	150
		Trofeo	Espabilador	100
Solution 3:
	Fitness: 1681.02
	Weapon damage: 1681.02
	Elemental damage: 1322.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 82.0
		vitalidad : 4810.0
		% resistencia neutral : 20.0
		% resistencia al fuego : 18.0
		% resistencia al aire : 34.0
		% resistencia al agua : 37.0
		% resistencia a la tierra : 35.0
	Characteristics:
		agilidad: 370.0
		suerte: 130.0
		inteligencia: 370.0
		fuerza: 370.0
		vitalidad: 4810.0
		sabiduría: 380.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de Pol Guatson	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa de Anerice	200
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Lokulto	20
		Sombrero	Gorro de Noai Aludem	198
		Trofeo	Lozano mayor	150
		Trofeo	Espabilador	100
Solution 4:
	Fitness: 1521.9499999999998
	Weapon damage: 1521.9499999999998
	Elemental damage: 1158.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 80.0
		vitalidad : 4510.0
		% resistencia neutral : 38.0
		% resistencia al fuego : 19.0
		% resistencia al aire : 36.0
		% resistencia al agua : 15.0
		% resistencia a la tierra : 20.0
	Characteristics:
		agilidad: 430.0
		suerte: 130.0
		inteligencia: 330.0
		fuerza: 470.0
		vitalidad: 4510.0
		sabiduría: 430.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de kukoloide	200
		Anillo	Anillo traicionero	199
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa de Fuji Gélifux	193
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Escudo	Escudo de kukoloide	200
		Espada	Espada maldita del gran Desangrador Guerrero	200
		Mascota	Microsmoglob	20
		Sombrero	Pendiente de Kongoku	200
		Trofeo	Hiperactivo	100
		Trofeo	Lozano mayor	150
		Trofeo	Nómada	100
Solution 5:
	Fitness: 1438.8
	Weapon damage: 1438.8
	Elemental damage: 1197.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 83.0
		vitalidad : 4745.0
		% resistencia neutral : 17.0
		% resistencia al fuego : 16.0
		% resistencia al aire : 21.0
		% resistencia al agua : 18.0
		% resistencia a la tierra : 25.0
	Characteristics:
		agilidad: 390.0
		suerte: 100.0
		inteligencia: 280.0
		fuerza: 850.0
		vitalidad: 4745.0
		sabiduría: 425.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto del Corazón Sangriento	200
		Anillo	Anillo de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capa de Fuji Gélifux	193
		Cinturón	Cinturón de Brus	194
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus Ocre	160
		Escudo	Escudo de kukoloide	200
		Espada	Garra de Gargandias	200
		Mascota	Microsmoglob	20
		Sombrero	Cuerno de Torkelonia	200
		Trofeo	Hércules mayor	150
		Trofeo	Rabioso mayor	150
		Trofeo	Lozano mayor	150
Solution 6:
	Fitness: 1265.1599999999999
	Weapon damage: 1265.1599999999999
	Elemental damage: 1063.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 83.0
		vitalidad : 4995.0
		% resistencia neutral : 22.0
		% resistencia al fuego : 28.0
		% resistencia al aire : 25.0
		% resistencia al agua : 24.0
		% resistencia a la tierra : 29.0
	Characteristics:
		agilidad: 350.0
		suerte: 100.0
		inteligencia: 300.0
		fuerza: 790.0
		vitalidad: 4995.0
		sabiduría: 445.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de kukoloide	200
		Anillo	Anillo de Corrupción	200
		Anillo	Alianza de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capachalote	200
		Cinturón	Cinturón de Brus	194
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus Marfil	180
		Escudo	Escudo de kukoloide	200
		Espada	Garra de Gargandias	200
		Mascota	Microsmoglob	20
		Sombrero	Cuerno de Torkelonia	200
		Trofeo	Hércules	100
		Trofeo	Hércules mayor	150
		Trofeo	Viajante	100
Solution 7:
	Fitness: 1260.3600000000001
	Weapon damage: 1260.3600000000001
	Elemental damage: 1359.0
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 81.0
		vitalidad : 5095.0
		% resistencia neutral : 17.0
		% resistencia al fuego : 16.0
		% resistencia al aire : 22.0
		% resistencia al agua : 20.0
		% resistencia a la tierra : 30.0
	Characteristics:
		agilidad: 310.0
		suerte: 230.0
		inteligencia: 310.0
		fuerza: 550.0
		vitalidad: 5095.0
		sabiduría: 480.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de estrígido	200
		Anillo	Anillo del conde Kontatrás	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capachalote	200
		Cinturón	Zarcinturón de Corrupción	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Martillo	Martillo seco	190
		Mascota	Microsmoglob	20
		Sombrero	Maskrobio	200
		Trofeo	Lozano mayor	150
		Trofeo	Espabilador	100
Solution 8:
	Fitness: 1222.5
	Weapon damage: 1222.5
	Elemental damage: 1339.5
	Preferences:
		PA : 12.0
		PM : 6.0
		% crítico : 80.0
		vitalidad : 5095.0
		% resistencia neutral : 18.0
		% resistencia al fuego : 16.0
		% resistencia al aire : 39.0
		% resistencia al agua : 30.0
		% resistencia a la tierra : 23.0
	Characteristics:
		agilidad: 360.0
		suerte: 170.0
		inteligencia: 360.0
		fuerza: 420.0
		vitalidad: 5095.0
		sabiduría: 470.0
	Items:
		Type	Description	Level
		Amuleto	Amuleto de estrígido	200
		Anillo	Anillo de Pol Guatson	200
		Anillo	Anillo de Corrupción	200
		Bota	Botas de kukoloide	200
		Capa	Capachalote	200
		Cinturón	Cinturón de estrígido	200
		Dofus	Dofus Púrpura	110
		Dofus	Dofus Turquesa	160
		Dofus	Dofus de los hielos	180
		Dofus	Dofus Ocre	160
		Dofus	Dolmanax	100
		Escudo	Escudo de kukoloide	200
		Martillo	Martillo de Kuatropatas	200
		Mascota	Microsmoglob	20
		Sombrero	Pendiente de Kongoku	200
		Trofeo	Lozano mayor	150

In [8]:
solution.totals_summary(effect_descriptions)#.sort_values("value",ascending=False)

                     description   value
0                Intercambiable:     0.0
8                             PM     6.0
9                      vitalidad  4945.0
10                     sabiduría   415.0
12                            PA    11.0
13                  inteligencia   420.0
15    de resistencia a la tierra    15.0
16         % resistencia al aire    36.0
17         % resistencia al agua    25.0
22                        suerte   400.0
24                    iniciativa  1000.0
25                   prospección    45.0
26                       placaje    50.0
27               de daño de agua    89.0
28                  invocaciones     1.0
29                     % crítico    82.0
31                       alcance     3.0
32    potencia (daños generales)   310.0
34         % resistencia neutral    17.0
36                      agilidad   310.0
37        % resistencia al fuego    16.0
38               de daño crítico   112.0
39   a la esquiva pérdidas de PM    37.0
45                        fuerza   570.0
46     de resistencia a críticos    35.0
47               de daño de aire    47.0
48             de daño de tierra    92.0
49                de daño neutro    80.0
50               al retiro de PM     6.0
59                         huida   -15.0
61              de daño de fuego    77.0
62             de daño de empuje    -1.0
63     % resistencia a la tierra    25.0
64               al retiro de PA   -15.0
70      de resistencia al empuje    20.0
72                          None     2.0
98                       Actitud   370.0
121                      de cura    92.0
163              -special spell-     0.0
195           de daños neutrales    38.0
214             de daños de agua    28.0
221            de robo de tierra    10.0
252                         None     1.0

In [9]:
set_summary = solution.set_summary()
set_summary

,type_id,type,description,level,set
694,13,Dofus,Dofus Púrpura,110,None
739,13,Dofus,Dofus Turquesa,160,None
7043,13,Dofus,Dofus de los hielos,180,None
11738,3,Anillo,Anillo Chanicomo,194,None
13344,13,Dofus,Dolmanax,100,None
13673,12,Mascota,Lokulto,20,None
13759,13,Trofeo,Hércules mayor,150,None
14093,5,Bota,Botas de kukoloide,200,Set de kukoloide
14168,11,Capa,Capa Pología,198,None
16332,13,Trofeo,Lozano mayor,150,None
18718,7,Escudo,Escudo de kukoloide,200,Set de kukoloide
19250,4,Cinturón,Cinturón del Espíritu Insano,200,Set del Espíritu Insano
19252,10,Sombrero,Máscara del Espíritu Insano,200,Set del Espíritu Insano
21223,3,Anillo,Coconillo,200,Set de Cocuzko
24029,1,Amuleto,Amuleto de Wulán,200,Set de Wulán
27540,2,Martillo,Martillo seco,190,Set de los Martilloseco

In [10]:
set_summary["set"].value_counts()

set
Set de kukoloide           2
Set del Espíritu Insano    2
Set de Cocuzko             1
Set de Wulán               1
Set de los Martilloseco    1
Name: count, dtype: int64

In [11]:
import matplotlib.pyplot as plt
plt.plot(opt.ga_instance.best_solutions_fitness)
plt.xlabel('Generation')
plt.ylabel('Best Fitness')

AttributeError: 'Optimizer' object has no attribute 'ga_instance'

In [ ]:
assert False

AssertionError:

In [7]:
# Current
chr = Chromosome([
                    8993, # Espada
                    13641, 13643, 13642, # Noai
                    14161, 14162, 14169, # Charlatan
                    19985, # Vuelo
                    18670, # Escudo
                    13673, # Lokulto
                    739, 694, 7754, 737, 7043, 17078 # Dofus
                 ],
                 opt)
chr.fitness

1890.67

In [ ]:
Items[Items["name"].str.contains("kuko")]

                       name               set  level
13989    Pluma de kukoloide              None    200
14091  Amuleto de kukoloide  Set de kukoloide    200
14092   Anillo de kukoloide  Set de kukoloide    200
14093    Botas de kukoloide  Set de kukoloide    200
13988      Ojo de kukoloide              None    200
18718   Escudo de kukoloide  Set de kukoloide    200

In [8]:
# Project
chr = Chromosome(
                 [
                    8993, # Espada
                    13641, 13642, # Noai
                    14161, 14162, 14169, # Charlatan
                    14092, 14093, 18718, # Kuko
                    13673, # Lokulto
                    739, 694, 7754, 737, 7043, 17078 # Dofus
                 ],
                 opt)
chr.fitness

2049.74

In [ ]:
chr.set_summary()

In [ ]:
chr.set_summary()["set"].value_counts()

In [ ]:
chr.totals_summary(effect_descriptions)

In [ ]:
Items[Items["name"].str.contains("Chani")]

In [ ]:
item = items[21392]
# item = items[6981]

In [ ]:
chr.are_item_conditions_met(item)

In [ ]:
item

In [ ]:
Items

In [ ]:
lst

In [ ]:
lst[0][2]

In [ ]:
chr.are_item_conditions_met(items[11738])

In [ ]:
items[11738]["conditions"]

In [ ]:
chr.totals[8]

In [ ]:
lst = []
for i in items.values():
    if i["type"]["superTypeId"] not in [i[0] for i in opt.pool_types]:
        continue
    if i["conditions"]:
        print(opt.solution.are_item_conditions_met(i))
        lst.append((i,opt.solution.are_item_conditions_met(i)))

In [ ]:
lst[1]

In [ ]:
lst.count(True), lst.count(False)