In [17]:
# Autoreload
%load_ext autoreload
%autoreload 2

import pygad
from scripts import Optimizer,Character,Chromosome
import json
with open('data/MAPPED_ITEMS.json', 'r') as file:
    items = {i["ankama_id"]: i for i in json.load(file)}

with open('data/MAPPED_SETS.json', 'r') as file:
    item_sets = {i["ankama_id"]: i for i in json.load(file)}

effect_descriptions = {}
for _,item in items.items():
    if not item["effects"]:
        continue
    for effect in item["effects"]:
        effect_descriptions[effect["element_id"]] = effect["type"]

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
char = Character(level=200)
config = {
            "language": "es",
            "population_size": 150,
            "num_generations": 1000,
            "mutation_rate": 0.05,
            "crossover_rate": 0.8,
            "parent_selection_type": "sss",  # Steady State Selection
            # "parent_selection_type": "tournament",  # Tournament Selection
            "exclusions": {
                "items": [6894,
                           6895,
                             3080,
                               9031]  # Excluded items
            },
            "preferences": {
                "lower": {
                    12: 11,  # AP
                    8: 5,   # MP
                },
                "upper": {} 
            }
        }
opt = Optimizer(char, items, item_sets, config)

Total pools: 16 with sizes [80, 168, 84, 84, 80, 93, 47, 107, 83, 145, 47, 47, 47, 47, 47, 47]

In [ ]:
opt.optimize()

In [ ]:
opt.solution.fitness

777.7520000000001

In [ ]:
opt.solution.totals_summary(effect_descriptions,
                      language=config["language"])

                     description   value
0                Intercambiable:     0.0
8                             PM     6.0
9                      vitalidad  3050.0
10                     sabiduría   460.0
12                            PA    11.0
13                  inteligencia   470.0
16         % resistencia al aire    26.0
17         % resistencia al agua     7.0
22                        suerte   290.0
25                   prospección    15.0
26                       placaje     0.0
27               de daño de agua    87.0
28                  invocaciones     3.0
29                     % crítico    18.0
31                       alcance     5.0
32    potencia (daños generales)   230.0
34         % resistencia neutral     5.0
36                      agilidad   200.0
37        % resistencia al fuego    33.0
38               de daño crítico    25.0
39   a la esquiva pérdidas de PM    27.0
45                        fuerza   250.0
46     de resistencia a críticos    50.0
47               de daño de aire    65.0
48             de daño de tierra    75.0
49                de daño neutro    75.0
50               al retiro de PM    12.0
59                         huida    50.0
61              de daño de fuego   122.0
63     % resistencia a la tierra    26.0
70      de resistencia al empuje   100.0
75   a la esquiva pérdidas de PA    10.0
81         Ligado a un personaje     0.0
98                       Actitud   182.0
121                      de cura    25.0
163              -special spell-     0.0
189             de daños de aire    15.0
194           de daños de tierra    15.0
198            de daños de fuego    15.0
214             de daños de agua    15.0

In [ ]:
opt.solution.set_summary(language=config["language"])

,type_id,type,description,set
7043,13,Dofus,Dofus de los hielos,None
7114,13,Dofus,Dofus Ébano,None
14089,3,Anillo,Anillo criocrono,Set criocrono
15700,4,Cinturón,Protozocalzón,Set de los krobios
18002,11,Capa,Capa de diondino,None
18711,7,Escudo,Escudo cubista,None
19249,10,Sombrero,Máscara del Espíritu de la Salvación,Set del Espíritu de la Salvación
19398,13,Dofus,Dofus forjalava,None
19608,3,Anillo,Anillo de famosillo,Set ahogado
19610,5,Bota,Zapautonimias,None
19984,1,Amuleto,Amuleto de vueloceronte,Set de vueloceronte
19986,2,Arco,Arco de vueloceronte,Set de vueloceronte
22007,13,Prismaradita,Pristeza iridiscente,None
22020,13,Prismaradita,Prisortilegio,None
29134,13,Dofus,Dofus silvestre,None
31885,12,Mascota,Microsmoglob,None

In [ ]:
elements = set()
for i in items.values():
    conditions = i["conditions"]
    if not conditions:
        continue
    dct = conditions["value"]
    if not dct:
        continue
    elements.add(dct["element"])

elements

{'CA',
 'CC',
 'CI',
 'CM',
 'CP',
 'CS',
 'CV',
 'CW',
 'PK',
 'PL',
 'PO',
 'PZ',
 'Pa',
 'Pk',
 'Po',
 'Pz',
 'ca',
 'cc',
 'ci',
 'cs',
 'cv',
 'cw'}

In [ ]:
conditions = set()
for i in opt.items.values():
    if not i.get("conditions"):
        continue
    for c in i["conditions"]:
        conditions.add(c["element"])

TypeError: string indices must be integers

In [ ]:
i["conditions"]

{'value': {'element': 'PZ',
  'element_id': 252,
  'operator': '=',
  'value': 1,
  'templated': {'de': 'Abonniert',
   'en': 'Be subscribed',
   'es': 'Estar abonado',
   'fr': 'Être abonné',
   'pt': 'Ser assinante'}},
 'is_operand': True,
 'relation': None,
 'children': None}

In [ ]:
opt.get_damage(opt.get_chromosome_weapon(solution), solution)

0.0

1476.225